In [73]:
import requests
from bs4 import BeautifulSoup

In [16]:
url = 'https://www.nykaa.com/'
# type this header (vali line) if don't get the response status code - 200.
headers = {
 "user-agent" : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36'
}
response = requests.get(url,headers = headers)

In [17]:
response.status_code

403

In [12]:
html_code = response.text

In [13]:
html_code[:2000]

'<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5, user-scalable=yes"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/ce7eab63e1459c4f.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/02f056cfe1c680cb.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/f5b9f46d405973ec.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/9de030976e28ab5b.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/68b7d95a0756276b.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/30a196209fd367b2.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/c0112a058374a858.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/be9056ed231109e5.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/38bc4fb3276c4715.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/6817942de1ae99c9.css" data-precedence="next"/><link rel="stylesheet" href="https://assets.cars24.com/production/india-website/catalog/260217235847/_next/static/css/ae7c1b7024669c3e.css" data-precedence="next"/><link rel="stylesheet" href="ht'

In [14]:
soup = BeautifulSoup(html_code) #Parsing

In [15]:
soup.text[:2000]

'Cars24: Buy & Sell Used Cars | Car Loan | New Car | Challan IndiaBuy used carBuy Used Cars in IndiaChange cityBrowse by CityBrowse by CityUsed Cars in Delhi NCRUsed Cars in BangaloreUsed Cars in New DelhiUsed Cars in HyderabadUsed Cars in MumbaiUsed Cars in PuneUsed Cars in AhmedabadUsed Cars in ChennaiUsed Cars in NoidaUsed Cars in GurgaonUsed Cars in GhaziabadUsed Cars in KolkataUsed Cars in LucknowUsed Cars in FaridabadUsed Cars in JaipurBuy cars onlineSell carSell carUsed car valuationSell car in DelhiSell car in MumbaiSell car in BangaloreSell car in HyderabadSell car in AhmedabadSell car in GurgaonSell car in ChennaiSell car in PuneSell car in NoidaSell car in GhaziabadSell car in LucknowSell car in JaipurSell car in KolkataSell car in KochiSell car in IndoreCar financeUsed car loanLoan against carPersonal loanCredit cardsUsed car loanOverviewFeatures & BenefitsApplication ProcessEMI CalculatorDocument & EligibilityInterest rates & chargesWhy LOANS24?Loan against carOverviewFeatures & BenefitsCalculatorDocument & EligibilityApplication ProcessInterest & ChargesPay your EMIPersonal loanOverviewFeatures & BenefitsEMI CalculatorDocument & EligibilityApplication ProcessInterest & Charges New carsPopular BrandsPopular CarsCar By Body TypeCars By Price RangeExplore new car CompareNews and ReviewsPopular BrandsPopular CarsHyundai CretaMahindra TharTata NexonTata PunchMaruti SwiftKia SeltosCar By Body TypeSedanSUVHatchbackMUVCars By Price RangeUnder 5 LakhsUnder 10 LakhsUnder 15 LakhsUnder 20 LakhsCar servicesCar servicesView & Pay ChallanCar Service HistoryCar ScrapCheck vehicle detailsPre delivery InspectionCall usHello, Sign inAccount LOG IN/SIGN UP Welcome tobetter drives,  better lives  View all carsThe Singapore Code on Take-overs and Mergers (Code) does not apply to Global Car Group Limited (GCGL) and the protections afforded by the Code do not apply to shareholders of GCGL, including the right to receive a minimum offer price from an offeror in a mandatory or '

In [109]:
html_soup = response.text

In [117]:
html_soup

'<!DOCTYPE html><html lang="en" class="__className_77cf4b"><head><meta charSet="UTF-8"/><meta charSet="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, viewport-fit=cover"/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="stylesheet" href="/nextui/_next/static/css/f12c77cc0282245f.css" data-precedence="next"/><link rel="preload" as="script" fetchPriority="low" href="/nextui/_next/static/chunks/webpack-be4a6f91a3135571.js"/><script src="/nextui/_next/static/chunks/js-chunks-909ec0239361cf2d.js" async=""></script><script src="/nextui/_next/static/chunks/main-app-6093c79f2f9bf624.js" async=""></script><script src="/nextui/_next/static/chunks/styles-c5e9a0e68d544364.js" async=""></script><script src="/nextui/_next/static/chunks/app/layout-7af09d8e38a5ed0c.js" async=""></script><script src="/nextui/_next/static/chunks/803-4c41de29d2f48c5e.js" async=""></script><script src="/nextui/_next/static/chunks/app/error-cb86564e764d0be1.js" async=""></script><link rel="icon" href="/nextui/images/favicon.ico"/><title>50% Off on Cheap, Luxury, Hotel Bookings Worldwide</title><meta name="description" content="Now Book Domestic &amp; International Hotels at Yatra.com. Travelers can book cheap, budget,luxury Chain hotels at great prices with the best discount ever"/><meta name="robots" content="noindex, nofollow"/><meta property="og:title" content="50% Off on Cheap, Luxury, Hotel Bookings Worldwide"/><meta property="og:description" content="Now Book Domestic &amp; International Hotels at Yatra.com. Travelers can book cheap, budget,luxury Chain hotels at great prices with the best discount ever"/><meta property="og:locale" content="en_US"/><meta property="og:type" content="website"/><meta name="twitter:card" content="summary"/><meta name="twitter:title" content="50% Off on Cheap, Luxury, Hotel Bookings Worldwide"/><meta name="twitter:description" content="Now Book Domestic &amp; International Hotels at Yatra.com. Travelers can book cheap, budget,luxury Chain hotels at great prices with the best discount ever"/><meta name="next-size-adjust"/><script src="/nextui/_next/static/chunks/polyfills-42372ed130431b0a.js" noModule=""></script></head><body><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MSCJN94" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><main><!--$?--><template id="B:0"></template><div></div><!--/$--></main><script src="/nextui/_next/static/chunks/webpack-be4a6f91a3135571.js" async=""></script><div hidden id="S:0"><template id="P:1"></template></div><script>(self.__next_f=self.__next_f||[]).push([0]);self.__next_f.push([2,null])</script><script>self.__next_f.push([1,"1:HL[\\"/nextui/_next/static/media/155cae559bbd1a77-s.p.woff2\\",\\"font\\",{\\"crossOrigin\\":\\"\\",\\"type\\":\\"font/woff2\\"}]\\n2:HL[\\"/nextui/_next/static/media/4de1fea1a954a5b6-s.p.woff2\\",\\"font\\",{\\"crossOrigin\\":\\"\\",\\"type\\":\\"font/woff2\\"}]\\n3:HL[\\"/nextui/_next/static/media/6d664cce900333ee-s.p.woff2\\",\\"font\\",{\\"crossOrigin\\":\\"\\",\\"type\\":\\"font/woff2\\"}]\\n4:HL[\\"/nextui/_next/static/media/7ff6869a1704182a-s.p.woff2\\",\\"font\\",{\\"crossOrigin\\":\\"\\",\\"type\\":\\"font/woff2\\"}]\\n5:HL[\\"/nextui/_next/static/css/f12c77cc0282245f.css\\",\\"style\\"]\\n"])</script><script>self.__next_f.push([1,"6:I[12846,[],\\"\\"]\\n9:I[4707,[],\\"\\"]\\nd:I[36423,[],\\"\\"]\\ne:I[88003,[\\"532\\",\\"static/chunks/styles-c5e9a0e68d544364.js\\",\\"185\\",\\"static/chunks/app/layout-7af09d8e38a5ed0c.js\\"],\\"\\"]\\n10:I[16395,[\\"532\\",\\"static/chunks/styles-c5e9a0e68d544364.js\\",\\"185\\",\\"static/chunks/app/layout-7af09d8e38a5ed0c.js\\"],\\"default\\"]\\n11:I[56490,[\\"532\\",\\"static/chunks/styles-c5e9a0e68d544364.js\\",\\"185\\",\\"static/chunks/app/layout-7af09d8e38a5ed0c.js\\"],\\"default\\"]\\n12:I[10376,[\\"532\\",\\"static/chunks/styles-c5e9a0e68d544364.js\\",\\"803\\",\\"static/chunks/803-4c41de29d2f48c5e.js\\",\\"601\\",\\"static/chunks/app/error-cb86564e764d0be1.js\\"],\\"default\\"]\\n14:I[61060,[],\\"\\"]\\na:[\\"hotelSearch\\",\\"hotel-search\\",\\"d\\"]\\nb:[\\"dom\\",\\"dom\\",\\"d\\"]\\nc:[\\"search\\",\\"search\\",\\"d\\"]\\nf:Ta20,"])</script><script>self.__next_f.push([1,"\\n            var webengage;\\n  ! function(w, e, b, n, g) {\\n    function o(e, t) {\\n      e[t[t.length - 1]] = function() {\\n        r.__queue.push([t.join(\\".\\"), arguments])\\n      }\\n    }\\n    var i, s, r = w[b],\\n      z = \\" \\",\\n      l = \\"init options track screen onReady\\".split(z),\\n      a = \\"feedback survey notification\\".split(z),\\n      c = \\"options render clear abort\\".split(z),\\n      p = \\"Open Close Submit Complete View Click\\".split(z),\\n      u = \\"identify login logout setAttribute\\".split(z);\\n    if (!r || !r.__v) {\\n      for (w[b] = r = {\\n          __queue: [],\\n          __v: \\"6.0\\",\\n          user: {}\\n        }, i = 0; i \\u003c l.length; i++) o(r, [l[i]]);\\n      for (i = 0; i \\u003c a.length; i++) {\\n        for (r[a[i]] = {}, s = 0; s \\u003c c.length; s++) o(r[a[i]], [a[i], c[s]]);\\n        for (s = 0; s \\u003c p.length; s++) o(r[a[i]], [a[i], \\"on\\" + p[s]])\\n      }\\n      for (i = 0; i \\u003c u.length; i++) o(r.user, [\\"user\\", u[i]])\\n    }\\n  }(window, document, \\"webengage\\");\\n\\n\\n  if (window.__WEBENGAGE_MOBILE_BRIDGE__) {\\n\\n    (function(bridge) {\\n\\n      var type = Object.prototype.toString;\\n\\n      webengage.user.login = webengage.user.identify = function(id) {\\n        bridge.login(id)\\n      };\\n      webengage.user.logout = function() {\\n        bridge.logout()\\n      };\\n\\n      webengage.user.setAttribute = function(name, value) {\\n        var attr = null;\\n\\n        if (type.call(name) === \'[object Object]\') {\\n          attr = name;\\n        } else {\\n          attr = {};\\n          attr[name] = value;\\n        }\\n\\n        if (type.call(attr) === \'[object Object]\') {\\n          bridge.setAttribute(JSON.stringify(attr));\\n        }\\n      };\\n\\n      webengage.screen = function(name, data) {\\n        if (arguments.length === 1 \\u0026\\u0026 type.call(name) === \'[object Object]\') {\\n          data = name;\\n          name = null;\\n        }\\n\\n        bridge.screen(name || null, type.call(data) === \'[object Object]\' ? JSON.stringify(data) : null);\\n      };\\n\\n      webengage.track = function(name, data) {\\n        bridge.track(name, type.call(data) === \'[object Object]\' ? JSON.stringify(data) : null);\\n      };\\n\\n    })(window.__WEBENGAGE_MOBILE_BRIDGE__);\\n\\n  } else {\\n\\n    setTimeout(function() {\\n      var f = document.createElement(\\"script\\"),\\n        d = document.getElementById(\\"_webengage_script_tag\\");\\n      f.type = \\"text/javascript\\",\\n      f.async = !0,\\n      f.src = (\\n      \\"https:\\" == window.location.protocol ?\\n       \\"https://widgets.in.webengage.com\\" : \\"http://widgets.in.webengage.com\\")\\n       + \\"/js/webengage-min-v-6.0.js\\",\\n      d.parentNode.insertBefore(f, d)\\n    });\\n\\n  }\\n\\n  webengage.init(\\"in~11b5641d1\\")"])</script><script>self.__next_f.push([1,"15:[]\\n"])</script><script>self.__next_f.push([1,"0:[\\"$\\",\\"$L6\\",null,{\\"buildId\\":\\"8NaI-Hy61r2v9r2WPIKhU\\",\\"assetPrefix\\":\\"/nextui\\",\\"urlParts\\":[\\"\\",\\"hotel-search\\",\\"dom\\",\\"search?checkoutDate=13%2F02%2F2026\\u0026checkinDate=12%2F02%2F2026\\u0026source=BOOKING_ENGINE\\u0026tenant=B2C\\u0026city.name=Goa\\u0026state.code=Goa\\u0026state.name=Goa\\u0026supplier=TGU\\u0026paymentMethod=\\u0026ci=\\u0026city.code=Goa\\u0026country.name=India\\u0026country.code=IND\\u0026roomRequests%5B0%5D.id=1\\u0026roomRequests%5B0%5D.noOfAdults=2\\u0026roomRequests%5B0%5D.noOfChildren=0\\"],\\"initialTree\\":[\\"\\",{\\"children\\":[[\\"hotelSearch\\",\\"hotel-search\\",\\"d\\"],{\\"children\\":[[\\"dom\\",\\"dom\\",\\"d\\"],{\\"children\\":[[\\"search\\",\\"search\\",\\"d\\"],{\\"children\\":[\\"__PAGE__?{\\\\\\"checkoutDate\\\\\\":\\\\\\"13/02/2026\\\\\\",\\\\\\"checkinDate\\\\\\":\\\\\\"12/02/2026\\\\\\",\\\\\\"source\\\\\\":\\\\\\"BOOKING_ENGINE\\\\\\",\\\\\\"tenant\\\\\\":\\\\\\"B2C\\\\\\",\\\\\\"city.name\\\\\\":\\\\\\"Goa\\\\\\",\\\\\\"state.code\\\\\\":\\\\\\"Goa\\\\\\",\\\\\\"state.name\\\\\\":\\\\\\"Goa\\\\\\",\\\\\\"supplier\\\\\\":\\\\\\"TGU\\\\\\",\\\\\\"paymentMethod\\\\\\":\\\\\\"\\\\\\",\\\\\\"ci\\\\\\":\\\\\\"\\\\\\",\\\\\\"city.code\\\\\\":\\\\\\"Goa\\\\\\",\\\\\\"country.name\\\\\\":\\\\\\"India\\\\\\",\\\\\\"country.code\\\\\\":\\\\\\"IND\\\\\\",\\\\\\"roomRequests[0].id\\\\\\":\\\\\\"1\\\\\\",\\\\\\"roomRequests[0].noOfAdults\\\\\\":\\\\\\"2\\\\\\",\\\\\\"roomRequests[0].noOfChildren\\\\\\":\\\\\\"0\\\\\\"}\\",{}]}]}]}]},\\"$undefined\\",\\"$undefined\\",true],\\"initialSeedData\\":[\\"\\",{\\"children\\":[[\\"hotelSearch\\",\\"hotel-search\\",\\"d\\"],{\\"children\\":[[\\"dom\\",\\"dom\\",\\"d\\"],{\\"children\\":[[\\"search\\",\\"search\\",\\"d\\"],{\\"children\\":[\\"__PAGE__\\",{},[[\\"$L7\\",\\"$L8\\",null],null],null]},[null,[\\"$\\",\\"$L9\\",null,{\\"parallelRouterKey\\":\\"children\\",\\"segmentPath\\":[\\"children\\",\\"$a\\",\\"children\\",\\"$b\\",\\"children\\",\\"$c\\",\\"children\\"],\\"error\\":\\"$undefined\\",\\"errorStyles\\":\\"$undefined\\",\\"errorScripts\\":\\"$undefined\\",\\"template\\":[\\"$\\",\\"$Ld\\",null,{}],\\"templateStyles\\":\\"$undefined\\",\\"templateScripts\\":\\"$undefined\\",\\"notFound\\":\\"$undefined\\",\\"notFoundStyles\\":\\"$undefined\\"}]],[[\\"$\\",\\"div\\",null,{}],[],[]]]},[null,[\\"$\\",\\"$L9\\",null,{\\"parallelRouterKey\\":\\"children\\",\\"segmentPath\\":[\\"children\\",\\"$a\\",\\"children\\",\\"$b\\",\\"children\\"],\\"error\\":\\"$undefined\\",\\"errorStyles\\":\\"$undefined\\",\\"errorScripts\\":\\"$undefined\\",\\"template\\":[\\"$\\",\\"$Ld\\",null,{}],\\"templateStyles\\":\\"$undefined\\",\\"templateScripts\\":\\"$undefined\\",\\"notFound\\":\\"$undefined\\",\\"notFoundStyles\\":\\"$undefined\\"}]],null]},[null,[\\"$\\",\\"$L9\\",null,{\\"parallelRouterKey\\":\\"children\\",\\"segmentPath\\":[\\"children\\",\\"$a\\",\\"children\\"],\\"error\\":\\"$undefined\\",\\"errorStyles\\":\\"$undefined\\",\\"errorScripts\\":\\"$undefined\\",\\"template\\":[\\"$\\",\\"$Ld\\",null,{}],\\"templateStyles\\":\\"$undefined\\",\\"templateScripts\\":\\"$undefined\\",\\"notFound\\":\\"$undefined\\",\\"notFoundStyles\\":\\"$undefined\\"}]],null]},[[[[\\"$\\",\\"link\\",\\"0\\",{\\"rel\\":\\"stylesheet\\",\\"href\\":\\"/nextui/_next/static/css/f12c77cc0282245f.css\\",\\"precedence\\":\\"next\\",\\"crossOrigin\\":\\"$undefined\\"}]],[\\"$\\",\\"html\\",null,{\\"lang\\":\\"en\\",\\"className\\":\\"__className_77cf4b\\",\\"children\\":[[\\"$\\",\\"head\\",null,{\\"children\\":[[\\"$\\",\\"link\\",null,{\\"rel\\":\\"icon\\",\\"href\\":\\"/nextui/images/favicon.ico\\"}],[\\"$\\",\\"meta\\",null,{\\"charSet\\":\\"UTF-8\\"}],[\\"$\\",\\"meta\\",null,{\\"name\\":\\"viewport\\",\\"content\\":\\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, viewport-fit=cover\\"}],[\\"$\\",\\"$Le\\",null,{\\"strategy\\":\\"lazyOnload\\",\\"id\\":\\"gtm-script\\",\\"dangerouslySetInnerHTML\\":{\\"__html\\":\\"\\\\n              (function(w,d,s,l,i){\\\\n      w[l]=w[l]||[];\\\\n      w[l].push({\'gtm.start\': new Date().getTime(), event:\'gtm.js\'});\\\\n      var f=d.getElementsByTagName(s)[0],\\\\n      j=d.createElement(s),dl=l!=\'dataLayer\'?\'\\u0026l=\'+l:\'\';\\\\n      j.async=true;\\\\n      j.src=\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;\\\\n      f.parentNode.insertBefore(j,f);\\\\n    })(window,document,\'script\',\'dataLayer\',\'GTM-MSCJN94\');\\\\n            \\"}}],[\\"$\\",\\"$Le\\",null,{\\"strategy\\":\\"lazyOnload\\",\\"id\\":\\"_webengage_script_tag\\",\\"type\\":\\"text/javascript\\",\\"dangerouslySetInnerHTML\\":{\\"__html\\":\\"$f\\"}}]]}],[\\"$\\",\\"body\\",null,{\\"children\\":[[\\"$\\",\\"noscript\\",null,{\\"children\\":[\\"$\\",\\"iframe\\",null,{\\"src\\":\\"https://www.googletagmanager.com/ns.html?id=GTM-MSCJN94\\",\\"height\\":\\"0\\",\\"width\\":\\"0\\",\\"style\\":{\\"display\\":\\"none\\",\\"visibility\\":\\"hidden\\"}}]}],[\\"$\\",\\"main\\",null,{\\"children\\":[\\"$\\",\\"$L10\\",null,{\\"children\\":[\\"$\\",\\"$L11\\",null,{\\"children\\":[\\"$\\",\\"$L9\\",null,{\\"parallelRouterKey\\":\\"children\\",\\"segmentPath\\":[\\"children\\"],\\"error\\":\\"$12\\",\\"errorStyles\\":[],\\"errorScripts\\":[],\\"template\\":[\\"$\\",\\"$Ld\\",null,{}],\\"templateStyles\\":\\"$undefined\\",\\"templateScripts\\":\\"$undefined\\",\\"notFound\\":[[\\"$\\",\\"title\\",null,{\\"children\\":\\"404: This page could not be found.\\"}],[\\"$\\",\\"div\\",null,{\\"style\\":{\\"fontFamily\\":\\"system-ui,\\\\\\"Segoe UI\\\\\\",Roboto,Helvetica,Arial,sans-serif,\\\\\\"Apple Color Emoji\\\\\\",\\\\\\"Segoe UI Emoji\\\\\\"\\",\\"height\\":\\"100vh\\",\\"textAlign\\":\\"center\\",\\"display\\":\\"flex\\",\\"flexDirection\\":\\"column\\",\\"alignItems\\":\\"center\\",\\"justifyContent\\":\\"center\\"},\\"children\\":[\\"$\\",\\"div\\",null,{\\"children\\":[[\\"$\\",\\"style\\",null,{\\"dangerouslySetInnerHTML\\":{\\"__html\\":\\"body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}\\"}}],[\\"$\\",\\"h1\\",null,{\\"className\\":\\"next-error-h1\\",\\"style\\":{\\"display\\":\\"inline-block\\",\\"margin\\":\\"0 20px 0 0\\",\\"padding\\":\\"0 23px 0 0\\",\\"fontSize\\":24,\\"fontWeight\\":500,\\"verticalAlign\\":\\"top\\",\\"lineHeight\\":\\"49px\\"},\\"children\\":\\"404\\"}],[\\"$\\",\\"div\\",null,{\\"style\\":{\\"display\\":\\"inline-block\\"},\\"children\\":[\\"$\\",\\"h2\\",null,{\\"style\\":{\\"fontSize\\":14,\\"fontWeight\\":400,\\"lineHeight\\":\\"49px\\",\\"margin\\":0},\\"children\\":\\"This page could not be found.\\"}]}]]}]}]],\\"notFoundStyles\\":[]}]}]}]}]]}]]}]],null],null],\\"couldBeIntercepted\\":false,\\"initialHead\\":[null,\\"$L13\\"],\\"globalErrorComponent\\":\\"$14\\",\\"missingSlots\\":\\"$W15\\"}]\\n"])</script><script>self.__next_f.push([1,"13:[[\\"$\\",\\"meta\\",\\"0\\",{\\"name\\":\\"viewport\\",\\"content\\":\\"width=device-width, initial-scale=1\\"}],[\\"$\\",\\"meta\\",\\"1\\",{\\"charSet\\":\\"utf-8\\"}],[\\"$\\",\\"title\\",\\"2\\",{\\"children\\":\\"50% Off on Cheap, Luxury, Hotel Bookings Worldwide\\"}],[\\"$\\",\\"meta\\",\\"3\\",{\\"name\\":\\"description\\",\\"content\\":\\"Now Book Domestic \\u0026 International Hotels at Yatra.com. Travelers can book cheap, budget,luxury Chain hotels at great prices with the best discount ever\\"}],[\\"$\\",\\"meta\\",\\"4\\",{\\"name\\":\\"robots\\",\\"content\\":\\"noindex, nofollow\\"}],[\\"$\\",\\"meta\\",\\"5\\",{\\"property\\":\\"og:title\\",\\"content\\":\\"50% Off on Cheap, Luxury, Hotel Bookings Worldwide\\"}],[\\"$\\",\\"meta\\",\\"6\\",{\\"property\\":\\"og:description\\",\\"content\\":\\"Now Book Domestic \\u0026 International Hotels at Yatra.com. Travelers can book cheap, budget,luxury Chain hotels at great prices with the best discount ever\\"}],[\\"$\\",\\"meta\\",\\"7\\",{\\"property\\":\\"og:locale\\",\\"content\\":\\"en_US\\"}],[\\"$\\",\\"meta\\",\\"8\\",{\\"property\\":\\"og:type\\",\\"content\\":\\"website\\"}],[\\"$\\",\\"meta\\",\\"9\\",{\\"name\\":\\"twitter:card\\",\\"content\\":\\"summary\\"}],[\\"$\\",\\"meta\\",\\"10\\",{\\"name\\":\\"twitter:title\\",\\"content\\":\\"50% Off on Cheap, Luxury, Hotel Bookings Worldwide\\"}],[\\"$\\",\\"meta\\",\\"11\\",{\\"name\\":\\"twitter:description\\",\\"content\\":\\"Now Book Domestic \\u0026 International Hotels at Yatra.com. Travelers can book cheap, budget,luxury Chain hotels at great prices with the best discount ever\\"}],[\\"$\\",\\"meta\\",\\"12\\",{\\"name\\":\\"next-size-adjust\\"}]]\\n7:null\\n"])</script><script>self.__next_f.push([1,"16:I[91726,[\\"532\\",\\"static/chunks/styles-c5e9a0e68d544364.js\\",\\"803\\",\\"static/chunks/803-4c41de29d2f48c5e.js\\",\\"119\\",\\"static/chunks/119-5abbe52a6ca8ac24.js\\",\\"763\\",\\"static/chunks/app/%5BhotelSearch%5D/%5Bdom%5D/%5Bsearch%5D/page-57c12ad8deaeecea.js\\"],\\"HotelListPage\\"]\\n1a:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"https://ns.yatracdn.com/strapi/qa/Avatar_e353474bca.png\\",\\"__typename\\":\\"UploadFile\\"}\\n19:{\\"Icon\\":\\"$1a\\",\\"Hover_Icon\\":null,\\"Code\\":\\"Offers\\",\\"External_URL\\":\\"https://www.yatra.com/offer/dom/listing/domestic-hotel-deals\\",\\"Label\\":\\"Offers\\",\\"Open_In_New_Tab\\":true,\\"Secondary_Label\\":null,\\"__typename\\":\\"Link\\"}\\n18:[\\"$19\\"]\\n17:{\\"Code\\":\\"OfferHeaderNav\\",\\"Label\\":\\"header Nav\\",\\"Links\\":\\"$18\\",\\"__typename\\":\\"NavigationItem\\"}\\n20:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"https://ns.yatracdn.com/strapi/dev/Hotel_b3330f8e5b.svg\\",\\"__typename\\":\\"UploadFile\\"}\\n21:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"https://ns.yatracdn.com/strapi/qa/Hotel_Red_3792d75f81.svg\\",\\"__typename\\":\\"UploadFile\\"}\\n1f:{\\"Icon\\":\\"$20\\",\\"Hover_Icon\\":\\"$21\\",\\"Code\\":\\"HotelsSearchBarHome\\",\\"External_URL\\":\\"https://www.yatra.com/hotels\\",\\"Label\\":\\"Hotels\\",\\"Open_In_New_Tab\\":true,\\"Secondary_Label\\":null,\\"__typename\\":\\"Link\\"}\\n1e:[\\"$1f\\"]\\n1d:{\\"Code\\":\\"HotelsNavSearchBar\\",\\"Label\\":\\"Hotels\\",\\"Links\\":\\"$1e\\",\\"__typename\\":\\"NavigationItem\\"}\\n25:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"https://ns.yatracdn.com/strapi/dev/p_LANE_e8c7340a95.svg\\",\\"__typename\\":\\"UploadFile\\"}\\n26:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"https://ns.yatracdn.com/strapi/qa/Flight_Red_817f0b9c12.svg\\",\\"__typename\\":\\"UploadFile\\"}\\n24:{\\"Icon\\":\\"$25\\",\\"Hover_Icon\\":\\"$26\\",\\"Code\\":\\"FlightsSearchBarHome \\",\\"External_URL\\":\\"https://www.yatra.com/flights\\",\\"Label\\":\\"Flights\\",\\"Open_In_New_Tab\\":true,\\"Secondary_Label\\":null,\\"__typename\\":\\"Link\\"}\\n23:[\\"$24\\"]\\n22:{\\"Code\\":\\"FlightNavSearchBar\\",\\"Label\\":\\"Flights\\",\\"Links\\":\\"$23\\",\\"__typename\\":\\"NavigationItem\\"}\\n2a:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"https://ns.yatracdn.com/strapi/dev/Artboard_2_a1bc298648.svg\\",\\"__typename\\":\\"UploadFile\\"}\\n2b:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"ht"])</script><script>self.__next_f.push([1,"tps://ns.yatracdn.com/strapi/qa/Holiday_Red_5760b252fe.svg\\",\\"__typename\\":\\"UploadFile\\"}\\n29:{\\"Icon\\":\\"$2a\\",\\"Hover_Icon\\":\\"$2b\\",\\"Code\\":\\"HolidaysSearchBarHome \\",\\"External_URL\\":\\"https://www.yatra.com/holidays\\",\\"Label\\":\\"Holidays\\",\\"Open_In_New_Tab\\":true,\\"Secondary_Label\\":null,\\"__typename\\":\\"Link\\"}\\n28:[\\"$29\\"]\\n27:{\\"Code\\":\\"HolidaysNavSearchBar\\",\\"Label\\":\\"Holidays\\",\\"Links\\":\\"$28\\",\\"__typename\\":\\"NavigationItem\\"}\\n2f:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"https://ns.yatracdn.com/strapi/dev/Bus_72936b9926.svg\\",\\"__typename\\":\\"UploadFile\\"}\\n30:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"https://ns.yatracdn.com/strapi/qa/Bus_Red_5755898334.svg\\",\\"__typename\\":\\"UploadFile\\"}\\n2e:{\\"Icon\\":\\"$2f\\",\\"Hover_Icon\\":\\"$30\\",\\"Code\\":\\"BusSearchBarHome\\",\\"External_URL\\":\\"https://www.yatra.com/bus-booking\\",\\"Label\\":\\"Bus\\",\\"Open_In_New_Tab\\":true,\\"Secondary_Label\\":null,\\"__typename\\":\\"Link\\"}\\n2d:[\\"$2e\\"]\\n2c:{\\"Code\\":\\"BusNavSearchBar\\",\\"Label\\":\\"Bus\\",\\"Links\\":\\"$2d\\",\\"__typename\\":\\"NavigationItem\\"}\\n34:{\\"caption\\":null,\\"alternativeText\\":null,\\"url\\":\\"https://ns.yatracdn.co

In [111]:
soup

<!DOCTYPE html>

# using Selenium

In [119]:
pip install selenium webdriver-manager pandas

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Collecting selenium
  Downloading selenium-4.40.0-py3-none-any.whl.metadata (7.7 kB)
Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pandas in e:\anaconda\lib\site-packages (2.2.3)
Collecting certifi>=2026.1.4 (from selenium)
  Using cached certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.32.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting trio-typing>=0.10.0 (from selenium)
  Downloading trio_typing-0.10.0-py3-none-any.whl.metadata (10 kB)
Collecting types-certifi>=2021.10.8.3 (from selenium)
  Downloading types_certifi-2021.10.8.3-py3-none-any.whl.metadata (1.4 kB)
Collecting types-urllib3>=1.26.25.14 (from selenium)
  Downloading types_urllib3-1.26.25.14-py3-none-any.whl.metadata (1.7 kB)
Collecting typing_extensions<5.0,>=4.15.0 (from selenium)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in e:\anaconda\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in e:\anaconda\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (24.3.0)
Requirement already satisfied: sortedcontainers in e:\anaconda\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in e:\anaconda\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.7)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in e:\anaconda\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in e:\anaconda\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.17.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in e:\anaconda\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: requests in e:\anaconda\lib\site-packages (from webdriver-manager) (2.32.3)
Requirement already satisfied: python-dotenv in e:\anaconda\lib\site-packages (from webdriver-manager) (1.1.0)
Requirement already satisfied: packaging in e:\anaconda\lib\site-packages (from webdriver-manager) (24.2)
Requirement already satisfied: numpy>=1.26.0 in e:\anaconda\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\anaconda\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: pycparser in e:\anaconda\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.21)
Requirement already satisfied: six>=1.5 in e:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mypy-extensions>=0.4.2 in e:\anaconda\lib\site-packages (from trio-typing>=0.10.0->selenium) (1.0.0)
Collecting async-generator (from trio-typing>=0.10.0->selenium)
  Downloading async_generator-1.10-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: importlib-metadata in e:\anaconda\lib\site-packages (from trio-typing>=0.10.0->selenium) (8.5.0)
Requirement already satisfied: h11<1,>=0.16.0 in e:\anaconda\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: zipp>=3.20 in e:\anaconda\lib\site-packages (from importlib-metadata->trio-typing>=0.10.0->selenium) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\anaconda\lib\site-packages (from requests->webdriver-manager) (3.3.2)
Downloading selenium-4.40.0-py3-none-any.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.6 MB 3.4 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.6 MB 3.7 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/9.6 MB 3.7 MB/s eta 0:00:02
   ------------- -------------------------- 3.1/9.6 MB 3.8 MB/s eta 0:00:02
   ---------------- ----------------------- 3.9/9.6 MB 3.8 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.6 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 5.8/9.6 MB 3.9 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.6 MB 4.0 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.6 MB 3.7 MB/s eta 0:00:01
   ------------------------------------- -- 8.9/9.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 3.7 MB/s eta 0:00:00
Downloading trio-0.32.0-py3-none-any.whl (512 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Using cached certifi-2026.1.4-py3-none-any.whl (152 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading trio_typing-0.10.0-py3-none-any.whl (42 kB)
Downloading types_certifi-2021.10.8.3-py3-none-any.whl (2.1 kB)
Downloading types_urllib3-1.26.25.14-py3-none-any.whl (15 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading async_generator-1.10-py3-none-any.whl (18 kB)
Installing collected packages: types-urllib3, types-certifi, wsproto, urllib3, typing_extensions, outcome, certifi, async-generator, trio, webdriver-manager, trio-websocket, trio-typing, selenium

   ------ ---------------------------------  2/13 [wsproto]
   --------- ------------------------------  3/13 [urllib3]
   --------- ------------------------------  3/13 [urllib3]
   --------- ------------------------------  3/13 [urllib3]
   --------- ------------------------------  3/13 [urllib3]
   --------- ------------------------------  3/13 [urllib3]
   --------- ------------------------------  3/13 [urllib3]
   ------------ ---------------------------  4/13 [typing_extensions]
   --------------- ------------------------  5/13 [outcome]
   --------------------- ------------------  7/13 [async-generator]
   --------------------- ------------------  7/13 [async-generator]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   ------------------------ ---------------  8/13 [trio]
   --------------------------- ------------  9/13 [webdriver-manager]
   --------------------------- ------------  9/13 [webdriver-manager]
   --------------------------- ------------  9/13 [webdriver-manager]
   ------------------------------ --------- 10/13 [trio-websocket]
   --------------------------------- ------ 11/13 [trio-typing]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ---------------------------------------- 13/13 [selenium]

Successfully installed async-generator-1.10 certifi-2026.1.4 outcome-1.3.0.post0 selenium-4.40.0 trio-0.32.0 trio-typing-0.10.0 trio-websocket-0.12.2 types-certifi-2021.10.8.3 types-urllib3-1.26.25.14 typing_extensions-4.15.0 urllib3-2.6.3 webdriver-manager-4.0.2 wsproto-1.3.2

### Scraping Data

# Lips

In [74]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,101):
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/makeup/lips/c/15?page_no={i}&sort=popularity&search_redirection=True"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "css-d5z3ro")

    if not containers:
        print("NO Products found,stopping.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [75]:
print(len(name_data))
print(len(review_data))
print(len(price_data))
print(len(discount_data))
print(len(og_price_data))
print(len(image_links))

40
40
40
40
40
40

In [76]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,Kay Beauty x Falguni Shane Peacock Luxe Matte ...,NaN,₹1799,NaN,( 182 ),https://images-static.nykaa.com/media/catalog/...
1,M.A.C Powder Kiss Hazy Matte Lipstick - Marrak...,NaN,₹2800,NaN,( 9 ),https://images-static.nykaa.com/media/catalog/...
2,e.l.f. Cosmetics Lip Lacquer - Wild Rose,NaN,₹400,NaN,( 27404 ),https://images-static.nykaa.com/media/catalog/...
3,Nykaa Cosmetics X Bridgerton Creamy Matte Long...,NaN,₹799,NaN,( 336 ),https://images-static.nykaa.com/media/catalog/...
4,Maybelline Serum Matte Lipstick - 8Hr hydratio...,₹599,₹569,5% Off,( 765 ),https://images-static.nykaa.com/media/catalog/...
5,LOreal Paris Infallible Matte Resistance Lipst...,₹999,₹899,10% Off,( 9140 ),https://images-static.nykaa.com/media/catalog/...
6,MARS Queen Of Mattes Reds & Maroons Liquid Lip...,₹499,₹469,6% Off,( 740 ),https://images-static.nykaa.com/media/Mostgift...
7,SUGAR Matte Attack Transferproof Lipstick,₹749,₹652,13% Off,( 34516 ),https://images-static.nykaa.com/media/Editor_P...
8,Lakme Be-Jewel Shimmer Lip Liquid with Ceramid...,₹1199,₹1079,10% Off,( 126 ),NaN
9,Charlotte Tilbury Big Lip Plumpgasm,NaN,₹3650,NaN,( 308 ),https://images-static.nykaa.com/media/bestof20...
10,Kay Beauty Hydra Creme Lipstick,NaN,₹1099,NaN,( 5443 ),https://images-static.nykaa.com/media/bestof20...
11,Nykaa Cosmetics So Creme! Creamy Matte Lipstick,₹329,₹214,35% Off,( 4035986 ),https://images-static.nykaa.com/media/Editor_P...
12,Nykaa Matte To Last ! Transferproof Liquid Lip...,₹749,₹487,35% Off,( 2394752 ),https://images-static.nykaa.com/media/Editor_P...
13,Maybelline New York Super Stay Matte Ink Liqui...,₹749,₹562,25% Off,( 3880801 ),https://images-static.nykaa.com/media/Editor_P...
14,Yves Saint Laurent The Inks Vinyl Cream Liquid...,NaN,₹4000,NaN,( 19 ),NaN
15,Maybelline New York Super Stay Vinyl Ink Liqui...,₹849,₹679,20% Off,( 47790 ),https://images-static.nykaa.com/media/Editor_P...
16,"Swiss Beauty Bold Matt Lip Liner Pencil, Long-...",NaN,₹69,NaN,( 264547 ),https://images-static.nykaa.com/media/Editor_P...
17,ETUDE Dear Darling Water Gel Lip and Cheek Tin...,₹450,₹405,10% Off,( 15988 ),https://images-static.nykaa.com/media/Editor_P...
18,Earth Rhythm Tender Tint For Lip & Cheek With ...,₹499,₹399,20% Off,( 50618 ),https://images-static.nykaa.com/media/Editor_P...
19,M.A.C MACximal Matte Lipstick,NaN,₹2550,NaN,( 316790 ),https://images-static.nykaa.com/media/bestof20...
20,"Lakme Forever Matte Liquid Lip Color, 16Hr Lip...",₹450,₹383,15% Off,( 228388 ),https://images-static.nykaa.com/media/catalog/...
21,Charlotte Tilbury Matte Revolution,NaN,₹3650,NaN,( 67561 ),https://images-static.nykaa.com/media/catalog/...
22,Revlon Super Lustrous Lipstick,₹999,₹899,10% Off,( 122147 ),https://images-static.nykaa.com/media/catalog/...
23,Maybelline New York Superstay Teddy Tint - Lip...,₹749,₹637,15% Off,( 4715 ),https://images-static.nykaa.com/media/catalog/...
24,MARS Edge Of Desire Lip Liner,NaN,₹69,NaN,( 48801 ),https://images-static.nykaa.com/media/catalog/...
25,Nykaa All Day Matte Long Lasting Transferproof...,₹399,₹259,35% Off,( 1108932 ),https://images-static.nykaa.com/media/Editor_P...
26,Nykaa Matte to Last No Transfer Long Lasting L...,NaN,₹599,NaN,( 1282 ),https://images-static.nykaa.com/media/bestof20...
27,Maybelline New York Sensational Liquid Matte L...,₹429,₹322,25% Off,( 282223 ),https://images-static.nykaa.com/media/Editor_P...
28,Maybelline Color Sensational Creamy Matte Lips...,₹329,₹263,20% Off,( 6910399 ),https://images-static.nykaa.com/media/Editor_P...
29,Maybelline New York Lifter Gloss,₹799,₹679,15% Off,( 15409 ),https://images-static.nykaa.com/media/Editor_P...
30,Huda Beauty Lip Contour Lip Stain,NaN,₹2100,NaN,( 5 ),NaN
31,Kay Beauty Matte Liquid Lipstick,₹1200,₹1080,10% Off,( 69316 ),https://images-static.nykaa.com/media/bestof20...
32,M.A.C MACximal Matte Mini Lipstick,NaN,₹1150,NaN,( 808806 ),https://images-static.nykaa.com/media/Mostgift...
33,"Lakme 9 To 5 Powerplay Priming Matte Lipstick,...",₹650,₹520,20% Off,( 95635 ),https://images-static.nykaa.com/media/Editor_P...
34,NYX Professional Makeup Lip Lingerie Xxl Matte...,₹899,₹854,5% Off,( 3151 ),https://images-static.nykaa.com/media/Editor_P...
35,MARS Candylicious Colored Lip Gloss,₹249,₹237,5% Off,( 8145 ),https://images-static.nykaa.com/media/Editor_P...
36,MARS Matte Muse Lipstick,₹299,₹278,7% Off,( 2525 ),https://images-static.nykaa.com/media/bestof20...
37,Nykaa Matte-illicious Transferproof Lip Crayon...,₹799,₹519,35% Off,( 342217 ),https://images-static.nykaa.com/media/Editor_P...
38,Nykaa Cosmetics X Naagin Hot Sauce Plumping Li...,₹599,₹539,10% Off,( 57 ),NaN
39,LANEIGE Glaze Craze Tinted Lip Serum,NaN,₹1150,NaN,( 1258 ),https://images-static.nykaa.com/media/Editor_P...

In [ ]:
df.to_csv("Lips_Products.csv",index = False)

# Eyes

In [36]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import numpy as np 
import pandas as pd 
import os
import requests


name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}

# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,129):
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/makeup/eyes/c/14?page_no={i}&sort=popularity&ptype=lst&id=14&root=nav_2&dir=desc&order=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    #containers = soup.find_all("div" , attrs = {'class' : "css-llpqn7"})
    containers = soup.find_all("div" , attrs = {'class' : "productWrapper css-17nge1h"})

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)

            
print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [65]:
print(len(name_data))
print(len(review_data))
print(len(price_data))
print(len(discount_data))
print(len(og_price_data))
print(len(rating_data))
print(len(image_links))

40
40
40
40
40
40
40

# Face

In [70]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import numpy as np 
import pandas as pd 
import os
import requests 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}

# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,151):
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/makeup/face/c/13?page_no={i}&sort=popularity&ptype=lst&id=13&root=nav_2&dir=desc&order=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    #containers = soup.find_all("div" , attrs = {'class' : "css-llpqn7"})
    containers = soup.find_all("div" , attrs = {'class' : "productWrapper css-17nge1h"})

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)
            
        
print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [71]:
print(len(name_data))
print(len(review_data))
print(len(price_data))
print(len(discount_data))
print(len(og_price_data))
print(len(image_links))

40
40
40
40
40
40

# Makeup Kits and Combos

In [77]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,75):
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/makeup/makeup-kits-combos/c/22670?page_no={i}&sort=popularity&dir=desc&id=14&order=popularity&ptype=lst&redirectpath=slug&root=nav_2"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [78]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,Nykaa Tools & Accessories Makeup Essential Bru...,₹1399,₹1189,15% Off,( 13 ),https://images-static.nykaa.com/media/catalog/...
1,SUGAR Complete Makeup Kit - Medium,₹5301,₹4241,20% Off,( 822 ),https://images-static.nykaa.com/media/catalog/...
2,Nykaa Cosmetics So Creme Bestseller Creamy Mat...,₹658,₹461,30% Off,( 4215153 ),https://images-static.nykaa.com/media/catalog/...
3,Kay Beauty Intense Black 24H Kajal Eyeliner Duo,NaN,₹999,NaN,( 345 ),https://images-static.nykaa.com/media/catalog/...
4,Sanfe Quick Fix Hair & Eyebrow Touch Up Kit Gr...,₹269,₹256,5% Off,( 24 ),https://images-static.nykaa.com/media/catalog/...
5,PIXI On-The-Glow Mini Blush Duo Kit - Ruby + J...,NaN,₹2080,NaN,( 31 ),https://images-static.nykaa.com/media/catalog/...
6,Maybelline New York Colossal Kajal (Pack Of 3),₹660,₹561,15% Off,( 187722 ),NaN
7,Parul Garg Beauty Ultimate Silk Matte Collecti...,NaN,₹990,NaN,( 701 ),https://images-static.nykaa.com/media/Editor_P...
8,Daily Life Forever52 16 Color Camouflage HD Co...,₹3099,₹2789,10% Off,( 3220 ),https://images-static.nykaa.com/media/bestof20...
9,Parul Garg Beauty Signature Classic Red Sindoo...,NaN,₹395,NaN,( 1552 ),https://images-static.nykaa.com/media/Editor_P...
10,Swiss Beauty Glow and Fix Combo,₹718,₹574,20% Off,( 288359 ),NaN
11,Maybelline New York The Colossal Combo - Masca...,₹1038,₹664,36% Off,( 661123 ),NaN
12,Love Earth Liquid Mousse Matte Lipstick,₹714,₹250,65% Off,( 2010 ),https://images-static.nykaa.com/media/bestof20...
13,PIXI PH Duo - Cheektone And Liptone,NaN,₹2300,NaN,( 6 ),https://images-static.nykaa.com/media/Mostgift...
14,Insight Cosmetics All Things Good Kit,₹2540,₹2032,20% Off,( 1142323 ),NaN
15,SUGAR Contour De Force Face Palette,₹799,₹695,13% Off,( 38922 ),https://images-static.nykaa.com/media/bestof20...
16,Swiss Beauty Bold Matte Lips Liner Pencil Set ...,₹207,₹176,15% Off,( 66174 ),NaN
17,Daily Life Forever52 Sensational 3 Color Eyebr...,₹625,₹531,15% Off,( 1 ),NaN
18,Recode Clay Matte Liquid Lipstick - Set Of 10,₹899,₹809,10% Off,( 130 ),https://images-static.nykaa.com/media/Editor_P...
19,RENEE Stay Forever Matte Liquid Lipstick Combo...,₹750,₹659,12% Off,( 858 ),https://images-static.nykaa.com/media/bestof20...
20,"MARS Trio Treat, 3-In-1 Eye Makeup Kit With Ey...",₹649,₹617,5% Off,( 319 ),https://images-static.nykaa.com/media/catalog/...
21,SUGAR POP All Set To Slay Makeup Kit,₹1479,₹1213,18% Off,NaN,https://images-static.nykaa.com/media/catalog/...
22,Maybelline New York Superstay Vinyl Ink Liquid...,₹3396,₹2377,30% Off,( 22784 ),https://images-static.nykaa.com/media/catalog/...
23,Blue Heaven Matte Love Long Lasting Hydrating ...,₹399,₹299,25% Off,( 5578 ),https://images-static.nykaa.com/media/catalog/...
24,Charlotte Tilbury Pillow Talk Icons On The Go,₹5750,₹5175,10% Off,( 7 ),https://images-static.nykaa.com/media/catalog/...
25,IRIS COSMETICS Luminous Face Brush Set,₹5499,₹4399,20% Off,( 2 ),https://images-static.nykaa.com/media/catalog/...
26,Insight Cosmetics All Things Good Kit - Mini,₹2055,₹1747,15% Off,( 1076808 ),NaN
27,Sotrue Strobe Cream Combo Pack (Gold & Pink),₹698,₹572,18% Off,( 76 ),NaN
28,Maybelline New York Superstay Matte Ink Liquid...,₹2996,₹1947,35% Off,( 3994711 ),NaN
29,C2P Pro Ultra HD 12 in 1 Camouflage Concealer ...,₹2499,₹1749,30% Off,( 18 ),NaN
30,Huda Beauty Glossiest Gloss Trio,NaN,₹2900,NaN,( 24 ),https://images-static.nykaa.com/media/Mostgift...
31,Charlotte Tilbury Mini Viral Beauty Icons,₹5600,₹4760,15% Off,( 4 ),NaN
32,Recode Silky Matte Liquid Lipstick - Pack Of 10,₹749,₹674,10% Off,( 2467 ),https://images-static.nykaa.com/media/Editor_P...
33,Lakme Forever Matte Nude Dream + Nude Twist Li...,₹900,₹765,15% Off,( 65163 ),NaN
34,MARS City Paradise Makeup Kit,₹499,₹474,5% Off,( 4777 ),https://images-static.nykaa.com/media/Mostgift...
35,Feel Good Club Blender Besties - 7 Makeup Spon...,₹499,₹304,39% Off,( 212 ),NaN
36,Renee Cosmetics All In 1 Professional Makeup B...,₹1200,₹849,29% Off,( 479 ),NaN
37,Nourish Mantra Liquid Lipstick Muted Magic Cre...,₹899,₹539,40% Off,( 412 ),NaN
38,Charlotte Tilbury Pillow Talk Iconic Lip & Che...,₹3650,₹3285,10% Off,( 19 ),NaN
39,Faces Canada Glow Getter Duo Hydra Mini Founda...,₹924,₹808,13% Off,( 17403 ),NaN

In [79]:
print(len(name_data))
print(len(review_data))
print(len(price_data))
print(len(discount_data))
print(len(og_price_data))
print(len(image_links))

40
40
40
40
40
40

# Nails

In [80]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,51):
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/makeup/nails/c/16?page_no={i}&sort=popularity&ptype=lst&id=16&root=nav_2&dir=desc&order=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [81]:
print(len(name_data))
print(len(review_data))
print(len(price_data))
print(len(discount_data))
print(len(og_price_data))
print(len(image_links))

40
40
40
40
40
40

In [82]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,Faces Canada Splash Nail Enamel,₹129,₹115,11% Off,( 3554906 ),https://images-static.nykaa.com/media/catalog/...
1,Nykaa Cosmetics Nail Enamel - Base BFF 373,₹119,₹107,10% Off,( 1035997 ),https://images-static.nykaa.com/media/catalog/...
2,Colors Queen Nail Affair Nail Polish,₹179,₹166,7% Off,( 65 ),https://images-static.nykaa.com/media/catalog/...
3,Colors Queen Move On Nail Polish Remove Pads -...,₹179,₹163,9% Off,( 12 ),https://images-static.nykaa.com/media/catalog/...
4,Hibiscus Monkey Nailed It Nail & Cuticle Treat...,₹579,₹492,15% Off,( 37 ),https://images-static.nykaa.com/media/catalog/...
5,Nykaa Creme Nail Enamel,₹229,₹195,15% Off,( 9513 ),https://images-static.nykaa.com/media/catalog/...
6,Nykaa Glitter Nail Enamel,₹249,₹212,15% Off,( 10344 ),NaN
7,MARS Cosmic Hues Nail Paint,NaN,₹99,NaN,( 786 ),NaN
8,HYUE Chrome Glazed Nail Paint,₹349,₹328,6% Off,( 77 ),NaN
9,Nykaa Stardust Holographic Long Lasting Chrome...,₹299,₹269,10% Off,( 287 ),NaN
10,Nykaa Cosmetics Nail Enamel,₹189,₹132,30% Off,( 10787709 ),https://images-static.nykaa.com/media/Editor_P...
11,Nykaa Cosmetics X Bridgerton Nail Polish,NaN,₹349,NaN,( 67 ),NaN
12,Sanfe Instant Stick On Nails-Classic Coffee Pa...,₹349,₹311,11% Off,( 25 ),NaN
13,Nykaa Cosmetics Breathable Nail Enamel,₹229,₹195,15% Off,( 855863 ),https://images-static.nykaa.com/media/Editor_P...
14,Kay Beauty Nail Nourish Nail Enamel Polish,₹259,₹220,15% Off,( 1168275 ),https://images-static.nykaa.com/media/Editor_P...
15,Nykaa Cosmetics Nail Care Range,₹259,₹233,10% Off,( 191130 ),https://images-static.nykaa.com/media/Editor_P...
16,HYUE Gel FX Nail Paint,₹299,₹278,7% Off,( 16 ),NaN
17,Wanderlust Coconut & Shea Butter Hand & Nail C...,₹299,₹239,20% Off,( 583726 ),https://images-static.nykaa.com/media/bestof20...
18,Nykaa Cosmetics Salon Shine Gel Nail Lacquer,₹325,₹276,15% Off,( 234475 ),https://images-static.nykaa.com/media/Editor_P...
19,Elle 18 Nail Pops Nail Polish,₹65,₹62,5% Off,( 8469825 ),https://images-static.nykaa.com/media/Editor_P...
20,HYUE Gel FX Nail Paint,₹299,₹278,7% Off,( 84 ),https://images-static.nykaa.com/media/catalog/...
21,Nykaa Cosmetics Matte Nail Enamel,₹229,₹137,40% Off,( 2687913 ),https://images-static.nykaa.com/media/catalog/...
22,Nykaa Cosmetics Insta Dry Fast Drying Nail Ena...,₹229,₹195,15% Off,( 812434 ),https://images-static.nykaa.com/media/catalog/...
23,Nykaa Stardust Holographic Long Lasting Chrome...,₹299,₹269,10% Off,( 287 ),https://images-static.nykaa.com/media/catalog/...
24,HYUE Plumping Top Coat,₹349,₹328,6% Off,( 12 ),https://images-static.nykaa.com/media/catalog/...
25,O.P.I Nail Lacquer,₹850,₹723,15% Off,( 268487 ),https://images-static.nykaa.com/media/catalog/...
26,MARS EURO Nail Lacquer,₹69,₹65,6% Off,( 2953 ),https://images-static.nykaa.com/media/Editor_P...
27,Coloressence Cute Coats Mini Nail Polish,₹60,₹57,5% Off,( 1216 ),https://images-static.nykaa.com/media/Editor_P...
28,Lakme Liquid Nail Polish Remover With Vitamin E,₹110,₹99,10% Off,( 22816 ),https://images-static.nykaa.com/media/Editor_P...
29,Insight Cosmetics Nail Polish Remover Wipes,₹55,₹53,3% Off,( 77704 ),https://images-static.nykaa.com/media/Editor_P...
30,Swiss Beauty Stunning Nail Lacquer,NaN,₹99,NaN,( 32419 ),https://images-static.nykaa.com/media/Editor_P...
31,"Lakme True Wear Color Crush Nail Polish, Long ...",₹150,₹135,10% Off,( 7330 ),https://images-static.nykaa.com/media/Editor_P...
32,Swiss Beauty Professional UV Gel Nail Polish,₹249,₹224,10% Off,( 5297 ),https://images-static.nykaa.com/media/Editor_P...
33,Nykaa Glitter Nail Enamel - Cocktail Toast 464,₹249,₹224,10% Off,( 10344 ),NaN
34,Lotus Professional PhytoRx Skin Anti-Ageing Fa...,₹965,₹820,15% Off,( 2704 ),https://images-static.nykaa.com/media/Editor_P...
35,Lakme Absolute Gel Stylist,₹350,₹315,10% Off,( 382723 ),NaN
36,Blue Heaven Instant Nail Paint Remover,₹45,₹44,3% Off,( 14236 ),https://images-static.nykaa.com/media/Editor_P...
37,Insight Cosmetics Nail Polish,₹50,₹48,5% Off,( 18618 ),https://images-static.nykaa.com/media/Editor_P...
38,Faces Canada Ultime Pro Splash Luxe Nail Enamel,₹249,₹209,16% Off,( 4021 ),NaN
39,Swiss Beauty Slay Nail Color Ultra Shine Formu...,₹129,₹123,5% Off,( 3293 ),NaN

# Tools and Brushes

In [83]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,125):
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/makeup/tools-brushes/c/217?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [84]:
print(len(name_data))
print(len(review_data))
print(len(price_data))
print(len(discount_data))
print(len(og_price_data))
print(len(image_links))

40
40
40
40
40
40

In [85]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,MORPHE Conceal & Set Tool Trio,NaN,₹2200,NaN,( 1 ),https://images-static.nykaa.com/media/catalog/...
1,Nykaa Tools 4-in-1 Travel Friendly Mini Brush ...,₹659,₹560,15% Off,( 13 ),https://images-static.nykaa.com/media/catalog/...
2,Nykaa Tools & Accessories BlendPro Foundation ...,₹499,₹374,25% Off,( 29420 ),https://images-static.nykaa.com/media/catalog/...
3,MORPHE Best Of Blends 8 Piece Face & Eye Brush...,NaN,₹4400,NaN,( 1 ),https://images-static.nykaa.com/media/catalog/...
4,MARS 4 In 1 Travel Brush,₹659,₹619,6% Off,( 4347 ),https://images-static.nykaa.com/media/catalog/...
5,Praush Beauty Celestial Super Soft Makeup Spon...,₹550,₹534,3% Off,( 5261 ),https://images-static.nykaa.com/media/catalog/...
6,"Swiss Beauty Professional Face & Eye Brush, So...",₹1299,₹909,30% Off,( 11574 ),https://images-static.nykaa.com/media/Mostgift...
7,Nykaa Tools Blend It! Jar -7 Makeup Sponges (4...,₹499,₹424,15% Off,( 7 ),NaN
8,MARS Tools Of Titan Brush With Holder - Pack Of 8,₹1199,₹1091,9% Off,( 1832 ),NaN
9,MARS Tools Of Titan Brush Set,₹999,₹899,10% Off,( 3716 ),NaN
10,Swiss Beauty Foundation Blender Brush,₹349,₹297,15% Off,( 10533 ),NaN
11,"MORPHE Ready, Set, Pro 16 Piece Face & Eye Bru...",NaN,₹8450,NaN,( 2 ),https://images-static.nykaa.com/media/OnlyatNy...
12,Bronson Professional Pink Ultimate Classic Bea...,₹400,₹60,85% Off,( 32896 ),NaN
13,MARS Artist's Arsenal Brush Set,₹1499,₹1349,10% Off,( 2345 ),NaN
14,Bronson Professional 20Pc Face & Eyes Makeup B...,₹1000,₹675,32% Off,( 3320 ),NaN
15,Nykaa Tools & Accessories Makeup Essential Bru...,₹1399,₹1189,15% Off,( 13 ),NaN
16,MARS Artist's Arsenal Ultra Thin Foundation Ma...,₹249,₹239,4% Off,( 220 ),NaN
17,Bronson Professional Super Soft Bristles Hd Fi...,₹550,₹350,36% Off,( 4219 ),NaN
18,MARS Artists Arsenal Angular Buffing Brush Gol...,₹299,₹269,10% Off,( 254 ),NaN
19,MORPHE Along For The Glide 6 Piece Travel Brus...,NaN,₹3150,NaN,( 2 ),https://images-static.nykaa.com/media/OnlyatNy...
20,Bronson Professional Premium 10 Pcs Makeup Bru...,₹450,₹360,20% Off,( 12195 ),https://images-static.nykaa.com/media/catalog/...
21,MARS Dual Purpose Sharpener,NaN,₹69,NaN,( 1865 ),https://images-static.nykaa.com/media/catalog/...
22,PAC Synthetic Series - Cruelty Free Soft Synth...,NaN,₹3795,NaN,( 99 ),https://images-static.nykaa.com/media/catalog/...
23,MORPHE M132 Angled Concealer Brush,NaN,₹1050,NaN,NaN,https://images-static.nykaa.com/media/catalog/...
24,PAC Absolute Basics - Amateur & Beginner MUA S...,NaN,₹4995,NaN,( 1310 ),https://images-static.nykaa.com/media/catalog/...
25,Beautiliss Glitter Dust Makeup Brush Set With ...,₹1000,₹300,70% Off,( 3011 ),https://images-static.nykaa.com/media/catalog/...
26,PAC Beginner Basic Face & Eye Brush Kit - Stur...,NaN,₹1895,NaN,( 193 ),NaN
27,MORPHE M161 Large Rounded Powder Brush,NaN,₹1500,NaN,NaN,https://images-static.nykaa.com/media/OnlyatNy...
28,Bronson Professional Pizza Puff Triangle Makeu...,₹325,₹68,79% Off,( 881 ),NaN
29,PAC 4-IN-1 Magnetic Makeup Brush - Innovative ...,₹995,₹945,5% Off,( 31 ),NaN
30,Feel Good Club Classic Makeup Blender Super So...,₹105,₹58,45% Off,( 259 ),NaN
31,MORPHE M104 Domed Foundation Brush,NaN,₹1600,NaN,( 3 ),https://images-static.nykaa.com/media/OnlyatNy...
32,PAC Translucent Powder,NaN,₹675,NaN,( 10274 ),NaN
33,Earth Rhythm Reusable Makeup Remover & Cleansi...,₹199,₹189,5% Off,( 4434 ),NaN
34,Swiss Beauty Powder Brush,₹349,₹314,10% Off,( 7587 ),NaN
35,Daily Life Forever52 A Skin-Like Blend Flat Fr...,₹399,₹339,15% Off,( 71 ),NaN
36,Bronson Professional Beauty Blender Sponge Mak...,₹325,₹50,85% Off,( 936 ),NaN
37,"VEGA Premium Eye Lash Curler for Women, Profes...",NaN,₹270,NaN,( 15166 ),NaN
38,PAC Concealer Brush 219 - Luxurious Dome Shape...,NaN,₹475,NaN,( 5350 ),NaN
39,MORPHE M103 Angled Cream & Liquid Foundation B...,NaN,₹1400,NaN,( 1 ),https://images-static.nykaa.com/media/OnlyatNy...

# SKIN CARE

# Moisturizers

In [87]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): # 114
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/skin/moisturizers/c/8393?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [88]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,CeraVe SA Smoothing Cream for Exfoliating Roug...,₹1100,₹1045,5% Off,( 4 ),https://images-static.nykaa.com/media/catalog/...
1,Clinique Moisture Surge 100h Auto-replenishing...,₹1200,₹950,21% Off,( 79183 ),https://images-static.nykaa.com/media/catalog/...
2,"Olay 7in1 Gel Moisturizer with Niacinamide, Vi...",₹799,₹495,38% Off,( 440 ),https://images-static.nykaa.com/media/catalog/...
3,Bobbi Brown Vitamin Enriched Face Base (Moistu...,NaN,₹7500,NaN,( 17412 ),https://images-static.nykaa.com/media/catalog/...
4,Nykaa Skin Hydra Plump Water Gel Creme Moistur...,₹499,₹424,15% Off,( 13 ),https://images-static.nykaa.com/media/catalog/...
5,Earth Rhythm Phyto Moisturiser,₹399,₹319,20% Off,( 4686 ),https://images-static.nykaa.com/media/catalog/...
6,Re'equil Ceramide & Hyaluronic Acid Moisturise...,₹295,₹280,5% Off,( 27908 ),NaN
7,Cetaphil Moisturising Cream,₹899,₹746,17% Off,( 146238 ),https://images-static.nykaa.com/media/bestof20...
8,Bioderma Niacinamide Moisturizer - Atoderm Cre...,NaN,₹699,NaN,( 37999 ),https://images-static.nykaa.com/media/bestof20...
9,CeraVe Moisturizer Cream For Dry Skin With Cer...,₹430,₹409,5% Off,( 41480 ),https://images-static.nykaa.com/media/bestof20...
10,Dot & Key Vitamin C + E Super Bright Face Mois...,₹495,₹426,14% Off,( 108127 ),https://images-static.nykaa.com/media/bestof20...
11,Dot & Key Hyaluronic + Ceramide Barrier Repair...,₹395,₹336,15% Off,( 105555 ),https://images-static.nykaa.com/media/bestof20...
12,Estee Lauder Advanced Night Repair Synchronize...,NaN,₹4500,NaN,( 55046 ),https://images-static.nykaa.com/media/bestof20...
13,Neutrogena Hydro Boost Hyaluronic Acid Water G...,₹1190,₹1071,10% Off,( 150167 ),https://images-static.nykaa.com/media/bestof20...
14,Simple Kind To Skin Hydrating Light Moisturiser,₹499,₹449,10% Off,( 52472 ),NaN
15,Plum 2% Niacinamide & Rice Water Moisturiser -...,₹525,₹473,10% Off,( 17996 ),https://images-static.nykaa.com/media/bestof20...
16,Embryolisse Lait-Creme Concentre,₹1525,₹1373,10% Off,( 35040 ),https://images-static.nykaa.com/media/Ontheris...
17,Ponds Super Light Gel Oil Free Moisturiser Wit...,₹830,₹623,25% Off,( 643331 ),https://images-static.nykaa.com/media/bestof20...
18,Dr.Althea 345 Relief Cream: Soothing & Barrier...,NaN,₹2499,NaN,( 734 ),https://images-static.nykaa.com/media/bestof20...
19,Cetaphil Moisturising Lotion,₹789,₹655,17% Off,( 193928 ),https://images-static.nykaa.com/media/bestof20...
20,Cetaphil DailyAdvance Ultra Hydrating Lotion,₹279,₹251,10% Off,( 133879 ),https://images-static.nykaa.com/media/catalog/...
21,Minimalist Vitamin B5 10% Moisturizer,NaN,₹349,NaN,( 75966 ),https://images-static.nykaa.com/media/catalog/...
22,Olay Super Collagen Peptides Moisturizer For F...,₹1999,₹1499,25% Off,( 252 ),https://images-static.nykaa.com/media/catalog/...
23,COSRX Advanced Snail Mucin 92 All In One Cream...,₹1650,₹1485,10% Off,( 15169 ),https://images-static.nykaa.com/media/catalog/...
24,Lakme Absolute Perfect Radiance Skin Brighteni...,₹415,₹374,10% Off,( 143119 ),https://images-static.nykaa.com/media/catalog/...
25,"CeraVe Moisturizer For Dry Skin, Barrier Repai...",₹1690,₹1606,5% Off,( 8560 ),https://images-static.nykaa.com/media/catalog/...
26,Forest Essentials Night Cream Eternal Youth Da...,NaN,₹2095,NaN,( 2589 ),NaN
27,Cetaphil BHR Brightening Night Comfort Cream,₹1299,₹1169,10% Off,( 13379 ),https://images-static.nykaa.com/media/bestof20...
28,CeraVe Moisturizing Body Lotion for Normal to ...,₹1750,₹1663,5% Off,( 12580 ),NaN
29,Plum BodyLovin Vanilla Caramello Bestselling B...,₹475,₹404,15% Off,( 28492 ),https://images-static.nykaa.com/media/bestof20...
30,The Formularx Barrier Relief Lightweight Ceram...,₹699,₹629,10% Off,( 448 ),NaN
31,"Ponds Youthful Miracle Hexyl Retinol Complex, ...",₹899,₹764,15% Off,( 100170 ),https://images-static.nykaa.com/media/bestof20...
32,NIVEA Soft Vit E Light Non Sticky Face Moistur...,₹660,₹396,40% Off,( 181832 ),NaN
33,Reequil 0.1% Retinol Night Creamtreat For Wrin...,₹395,₹375,5% Off,( 11587 ),https://images-static.nykaa.com/media/bestof20...
34,Dot & Key Strawberry Dew Brightening Moisturiz...,₹399,₹347,13% Off,( 999 ),NaN
35,Clayco Rice & Sake Sleeping Mask Night Gel Cre...,NaN,₹1099,NaN,( 1641 ),NaN
36,Charlotte Tilbury Charlotte's Magic Cream,₹6800,₹4080,40% Off,( 4488 ),https://images-static.nykaa.com/media/OnlyatNy...
37,La Roche-Posay Cicaplast Baume B5+ Repair Mois...,NaN,₹550,NaN,( 287 ),https://images-static.nykaa.com/media/OnlyatNy...
38,Episoft AC Moisturiser SPF 30 With Microencaps...,₹678,₹610,10% Off,( 19598 ),NaN
39,Cetaphil BHR Brightening Day Protection Cream SPF,₹1299,₹1169,10% Off,( 7885 ),NaN

# Serums

In [89]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #91
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/skin/serums/c/73006?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [90]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,The Ordinary Multi-Peptide + Copper Peptides 1...,NaN,₹2950,NaN,( 1073 ),https://images-static.nykaa.com/media/catalog/...
1,Celimax The Vita-A Retinal Shot Tightening Boo...,NaN,₹2199,NaN,( 529 ),https://images-static.nykaa.com/media/catalog/...
2,Plum 10% Niacinamide Brightening Face Serum wi...,₹659,₹593,10% Off,( 112027 ),https://images-static.nykaa.com/media/catalog/...
3,COSRX Advanced Snail 96 Mucin Power Essence,₹1450,₹1305,10% Off,( 58886 ),https://images-static.nykaa.com/media/catalog/...
4,Forest Essentials Advanced Soundarya Age Defyi...,NaN,₹2650,NaN,( 1510 ),https://images-static.nykaa.com/media/catalog/...
5,Estee Lauder Advanced Night Repair Synchronize...,NaN,₹4500,NaN,( 55046 ),https://images-static.nykaa.com/media/catalog/...
6,Minimalist 10% Vitamin C Serum For Face For Gl...,NaN,₹699,NaN,( 84736 ),https://images-static.nykaa.com/media/bestof20...
7,"Anua Niacinamide 10 Txa 4 Serum, Brightening K...",₹2000,₹1800,10% Off,( 453 ),https://images-static.nykaa.com/media/bestof20...
8,Cetaphil BHR Perfecting Serum,₹2299,₹1839,20% Off,( 2731 ),https://images-static.nykaa.com/media/Editor_P...
9,Minimalist 10% Niacinamide Face Serum With Mat...,NaN,₹599,NaN,( 120499 ),https://images-static.nykaa.com/media/bestof20...
10,Eucerin Anti-Pigment Dual Serum With Thiamidol...,₹3780,₹3402,10% Off,( 319 ),https://images-static.nykaa.com/media/Editor_P...
11,Dot & Key 10% Vitamin C + E Face Serum With 5%...,₹499,₹429,14% Off,( 49808 ),https://images-static.nykaa.com/media/bestof20...
12,Dr. Sheth's Argireline Peptide & Copper Peptid...,₹1499,₹1319,12% Off,( 69 ),NaN
13,The Ordinary Niacinamide 10% + Zinc 1%,NaN,₹600,NaN,( 153572 ),https://images-static.nykaa.com/media/Editor_P...
14,Minimalist 2% Salicylic Acid Face Serum For Bl...,NaN,₹549,NaN,( 70786 ),https://images-static.nykaa.com/media/bestof20...
15,Hyphen 18% Brightening + 20% Collagen Double S...,₹649,₹591,9% Off,( 908 ),https://images-static.nykaa.com/media/bestof20...
16,The Ordinary AHA 30% + BHA 2% Peeling Solution,NaN,₹950,NaN,( 22685 ),NaN
17,d'Alba piedmont White Truffle First Spray Seru...,₹1300,₹1170,10% Off,( 121 ),NaN
18,SKIN1004 Madagascar Centella Tone Brightening ...,₹999,₹949,5% Off,( 1561 ),https://images-static.nykaa.com/media/bestof20...
19,The Derma Co 2% Kojic Acid Face Serum for Dark...,₹499,₹439,12% Off,( 31708 ),https://images-static.nykaa.com/media/Editor_P...
20,"Olay 7in1 Serum with Niacinamide, Vitamin C, C...",₹799,₹599,25% Off,( 456 ),https://images-static.nykaa.com/media/catalog/...
21,Minimalist 2% Alpha Arbutin Face Serum With Bu...,NaN,₹549,NaN,( 60292 ),https://images-static.nykaa.com/media/catalog/...
22,Beauty Of Joseon Glow Deep Serum For Pigmentat...,NaN,₹1490,NaN,( 1729 ),https://images-static.nykaa.com/media/catalog/...
23,The Derma Co 10% Vitamin C Face Serum Reduces ...,₹649,₹571,12% Off,( 32908 ),https://images-static.nykaa.com/media/catalog/...
24,The Ordinary Hyaluronic Acid 2% + B5,NaN,₹1000,NaN,( 28844 ),https://images-static.nykaa.com/media/catalog/...
25,Plum 15% Vitamin C Glow Face Serum - Dermat Te...,₹790,₹711,10% Off,( 135476 ),https://images-static.nykaa.com/media/catalog/...
26,Foxtale Brightening Vitamin C Face Serum With ...,₹645,₹516,20% Off,( 12275 ),https://images-static.nykaa.com/media/bestof20...
27,The Derma Co 10% Niacinamide Face Serum For Ac...,₹599,₹509,15% Off,( 67415 ),NaN
28,"Olay Regenerist Micro Sculpting Serum, Plump &...",₹1799,₹1619,10% Off,( 1653 ),https://images-static.nykaa.com/media/Editor_P...
29,"La Roche-Posay Mela B3 Serum, For Anti-Dark Sp...",NaN,₹3300,NaN,( 44 ),https://images-static.nykaa.com/media/OnlyatNy...
30,Hyphen Golden Hour Glow Serum 56% Glow Hyphene...,₹649,₹591,9% Off,( 3101 ),https://images-static.nykaa.com/media/Ontheris...
31,Pilgrim 10% Vitamin C Face Serum For Daily Bri...,₹645,₹548,15% Off,( 2136 ),NaN
32,Dot & Key Blueberry Hydrate 12% Barrier Boost ...,₹599,₹497,17% Off,( 426 ),NaN
33,Beauty Of Joseon Glow Serum - Propolis + Niaci...,NaN,₹1480,NaN,( 1515 ),NaN
34,Asaya Depigmentation Underarm Spray for Dark U...,₹499,₹449,10% Off,( 287 ),https://images-static.nykaa.com/media/bestof20...
35,Pilgrim 25% AHA + 2% BHA + 5% PHA Peeling Solu...,₹945,₹822,13% Off,( 9189 ),NaN
36,The Formularx Gentle Retinol Night Serum For A...,₹699,₹629,10% Off,( 325 ),NaN
37,Beauty of Joseon Ginseng Essence Water,NaN,₹1570,NaN,( 4923 ),https://images-static.nykaa.com/media/bestof20...
38,Minimalist 10% Vitamin C Serum For Face For Gl...,NaN,₹299,NaN,( 84736 ),NaN
39,COSRX The 6 Peptide Skin Booster Serum,₹2050,₹1845,10% Off,( 878 ),NaN

# Cleansers

In [91]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #108
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/skin/cleansers/c/8378?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [92]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,"Nykaa Anti-Acne Face Wash With Salicylic Acid,...",₹279,₹237,15% Off,( 872594 ),https://images-static.nykaa.com/media/catalog/...
1,"Simple Refreshing Facial Wash, 100% Soap-Free ...",₹420,₹378,10% Off,( 177950 ),https://images-static.nykaa.com/media/catalog/...
2,Cetaphil Gentle Skin Cleanser,₹459,₹404,12% Off,( 367221 ),https://images-static.nykaa.com/media/catalog/...
3,Cetaphil Oily Skin Cleanser,₹1149,₹977,15% Off,( 81530 ),https://images-static.nykaa.com/media/catalog/...
4,Minimalist 2% Salicylic Acid + LHA Face Cleans...,NaN,₹299,NaN,( 119361 ),https://images-static.nykaa.com/media/catalog/...
5,CeraVe Hydrating Cleanser Non-Foaming Face Was...,₹330,₹314,5% Off,( 37876 ),https://images-static.nykaa.com/media/catalog/...
6,CeraVe Foaming Cleanser Face Wash For Oily Ski...,₹520,₹494,5% Off,( 20012 ),https://images-static.nykaa.com/media/bestof20...
7,Garnier Skin Naturals Micellar Oil-Infused Cle...,₹499,₹439,12% Off,( 269430 ),https://images-static.nykaa.com/media/Editor_P...
8,Dot & Key Barrier Repair + Hydrating Gentle Fa...,₹249,₹214,14% Off,( 53905 ),https://images-static.nykaa.com/media/bestof20...
9,The Derma Co Sali-Cinamide Anti-Acne Face Wash...,₹449,₹395,12% Off,( 18205 ),NaN
10,ClayCo Matcha Enzyme Dead Skin Removal Scrub,NaN,₹799,NaN,( 440 ),https://images-static.nykaa.com/media/bestof20...
11,The Derma Co Sali-Cinamide Anti-Acne Face Wash...,₹449,₹395,12% Off,( 18205 ),https://images-static.nykaa.com/media/bestof20...
12,Bioderma Pigmentbio Foaming Cream Brightening ...,NaN,₹1199,NaN,( 7744 ),https://images-static.nykaa.com/media/Editor_P...
13,The Derma Co 2% Niacinamide Gentle Skin Cleanser,₹299,₹275,8% Off,( 1479 ),NaN
14,Bioderma Dermatological Micellar Water Sensibi...,NaN,₹1299,NaN,( 44488 ),https://images-static.nykaa.com/media/Editor_P...
15,The Face Shop Rice Water Bright Foaming Cleanser,₹899,₹854,5% Off,( 45699 ),https://images-static.nykaa.com/media/bestof20...
16,Bioderma Cleanser - Sebium Gel Moussant - Acne...,NaN,₹899,NaN,( 12500 ),https://images-static.nykaa.com/media/Editor_P...
17,SKIN1004 Madagascar Centella Light Cleansing Oil,₹699,₹664,5% Off,( 456 ),NaN
18,Dot & Key Cica Salicylic & Green Tea Facewash ...,₹249,₹214,14% Off,( 62574 ),NaN
19,Plum 2% Niacinamide Face Wash With Rice Water ...,₹375,₹338,10% Off,( 8593 ),https://images-static.nykaa.com/media/bestof20...
20,Cetaphil BHR Brightness Reveal Creamy Cleanser,₹799,₹719,10% Off,( 7900 ),https://images-static.nykaa.com/media/catalog/...
21,Avene Cleanance Cleansing Gel,NaN,₹1250,NaN,( 5307 ),https://images-static.nykaa.com/media/catalog/...
22,The Derma Co 1% Kojic Acid Face Wash I Reduces...,₹299,₹269,10% Off,( 9724 ),https://images-static.nykaa.com/media/catalog/...
23,The Derma Co Sali-Cinamide Anti-Acne Face Wash...,₹249,₹224,10% Off,( 18205 ),https://images-static.nykaa.com/media/catalog/...
24,Dot & Key Vitamin C + E Super Bright Gel Face ...,₹249,₹214,14% Off,( 24671 ),https://images-static.nykaa.com/media/catalog/...
25,Vilvah Milk Powder Face Wash For Deep Cleansin...,NaN,₹499,NaN,( 93 ),https://images-static.nykaa.com/media/catalog/...
26,Plum Green Tea Pore Cleansing Gel Face Wash Wi...,₹360,₹324,10% Off,( 107545 ),https://images-static.nykaa.com/media/Editor_P...
27,Clinique Take The Day Off Cleansing Balm (Make...,₹1550,₹1200,23% Off,( 10521 ),https://images-static.nykaa.com/media/Editor_P...
28,Garnier Skin Naturals Micellar Oil-Infused Cle...,₹275,₹253,8% Off,( 94152 ),https://images-static.nykaa.com/media/Editor_P...
29,La Roche-Posay Mela B3 Anti-Dark Spot Face Was...,NaN,₹1450,NaN,( 51 ),https://images-static.nykaa.com/media/OnlyatNy...
30,CeraVe Blemish Control Cleanser With 2% Salicy...,₹1250,₹1188,5% Off,( 732 ),NaN
31,Foxtale Super Glow Face Wash Vitamin C + Papay...,₹329,₹283,14% Off,( 2532 ),NaN
32,Neutrogena Oil Free Acne Cleansing Face Wash w...,₹850,₹769,10% Off,( 13071 ),https://images-static.nykaa.com/media/bestof20...
33,"DHC Beauty Deep Cleansing Oil, Makeup Remover ...",₹1690,₹1521,10% Off,( 2558 ),https://images-static.nykaa.com/media/Editor_P...
34,Anua Heartleaf Quercetinol Pore Deep Cleansing...,₹1150,₹1035,10% Off,( 279 ),https://images-static.nykaa.com/media/OnlyatNy...
35,Anua Heartleaf Pore Control Cleansing Oil Remo...,₹1650,₹1485,10% Off,( 165 ),https://images-static.nykaa.com/media/bestof20...
36,Ethiglo Skin Lightening Face Wash,₹260,₹234,10% Off,( 2691 ),https://images-static.nykaa.com/media/Editor_P...
37,Simple Water Boost Micellar Facial Wash,₹450,₹405,10% Off,( 2067 ),NaN
38,"CeraVe SA Smoothing Cleanser For Dry, Rough & ...",₹1250,₹1188,5% Off,( 608 ),NaN
39,Innisfree Volcanic Clusters BHA Foaming Daily ...,₹800,₹720,10% Off,( 13231 ),https://images-static.nykaa.com/media/Editor_P...

# Masks

In [93]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #65
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/skin/masks/c/8399?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [94]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,"Nykaa Skin Real Collagen Mask – Hydrates, Brig...",₹325,₹260,20% Off,( 312 ),https://images-static.nykaa.com/media/catalog/...
1,Nykaa Skin Hydrogel Under-Eye Patches for Dark...,₹149,₹127,15% Off,( 110 ),https://images-static.nykaa.com/media/catalog/...
2,O3+ Blueberry D-TAN Face Pack for Tan Removal ...,₹1550,₹1395,10% Off,( 1385 ),https://images-static.nykaa.com/media/catalog/...
3,"Foxtale De-Tan Skin Radiance Mask, With Lactic...",₹545,₹474,13% Off,( 8655 ),https://images-static.nykaa.com/media/catalog/...
4,Nykaa Green Tea + Aloe Vera Sheet Mask For Hyd...,₹100,₹80,20% Off,( 7299318 ),https://images-static.nykaa.com/media/catalog/...
5,Clayco Rice & Sake Sleeping Mask Night Gel Cre...,NaN,₹1099,NaN,( 1641 ),https://images-static.nykaa.com/media/catalog/...
6,The Ordinary AHA 30% + BHA 2% Peeling Solution,NaN,₹950,NaN,( 22685 ),NaN
7,O3+ D -TAN Face Pack for Tan Removal & Glowing...,NaN,₹1550,NaN,( 41481 ),NaN
8,Biodance Bio-Collagen Real Deep Mask,NaN,₹380,NaN,( 479 ),https://images-static.nykaa.com/media/bestof20...
9,"O3+ D-TAN Face Pack for Tan Removal, Brighteni...",NaN,₹830,NaN,( 41481 ),NaN
10,Clayco De Tan Brightening Rice Pudding Face Pa...,NaN,₹999,NaN,( 92 ),https://images-static.nykaa.com/media/Ontheris...
11,Innisfree Pore Clearing Clay Mask 2X With Volc...,₹1100,₹990,10% Off,( 32184 ),NaN
12,TONYMOLY Korean I'm Face Sheet Mask,NaN,₹100,NaN,( 154607 ),https://images-static.nykaa.com/media/Ontheris...
13,Nykaa Skin Secrets Tea Tree & Salicylic Acid K...,₹100,₹80,20% Off,( 38724 ),https://images-static.nykaa.com/media/OnlyatNy...
14,The Pink Foundry Pore Refining & Soothing Clay...,₹749,₹599,20% Off,( 145 ),https://images-static.nykaa.com/media/Ontheris...
15,LANEIGE Bouncy And Firm Sleeping Mask,NaN,₹2600,NaN,( 940 ),NaN
16,Beauty of Joseon Red Bean Refreshing Pore Mask,NaN,₹1790,NaN,( 602 ),NaN
17,The Face Shop Real Nature Face Mask,NaN,₹100,NaN,( 175139 ),NaN
18,Forest Essentials Roop Nikhar & Gulab Ubtan Ay...,NaN,₹675,NaN,( 142 ),NaN
19,Raaga Professional De-Tan Removal Cream,₹414,₹373,10% Off,( 17223 ),NaN
20,TONYMOLY Korean Pureness 100 Face Sheet Mask,NaN,₹100,NaN,( 88084 ),https://images-static.nykaa.com/media/catalog/...
21,Nykaa Pearl + Hyaluronic Acid Sheet Mask For G...,₹100,₹80,20% Off,( 7299318 ),https://images-static.nykaa.com/media/catalog/...
22,Dot & Key Anti-Acne Salicylic Green Clay Face ...,₹550,₹468,15% Off,( 7944 ),https://images-static.nykaa.com/media/catalog/...
23,Raaga Professional De Tan Removal Creme With K...,₹1495,₹1346,10% Off,( 7995 ),https://images-static.nykaa.com/media/catalog/...
24,RENEE Pink Therapy Collagen Night Wrapping Fac...,₹599,₹555,7% Off,( 87 ),https://images-static.nykaa.com/media/catalog/...
25,Beauty of Joseon Ground Rice And Honey Glow Mask,NaN,₹1570,NaN,( 62 ),https://images-static.nykaa.com/media/catalog/...
26,"Dot & Key Mango Detan Clay Mask, With Alpha-Ar...",₹499,₹424,15% Off,( 186 ),NaN
27,Sanfe Deep Purifying Nose Strips for Women Pac...,₹169,₹157,7% Off,( 19167 ),NaN
28,"FoxTale Cherry-Collagen Clay Mask - Plumps, Hy...",₹649,₹565,13% Off,( 80 ),NaN
29,Nykaa Gold Sheet Mask For Revitalized & Youthf...,₹100,₹80,20% Off,( 7299638 ),https://images-static.nykaa.com/media/OnlyatNy...
30,Neude Instant Detanning + Hydrating + Brighten...,₹599,₹497,17% Off,( 26 ),NaN
31,Nykaa Naturals Korean Sheet Mask – Red Wine & ...,₹100,₹80,20% Off,( 7299638 ),https://images-static.nykaa.com/media/OnlyatNy...
32,Nua Pimple Patch for Acne - 36 Hydrocolloid an...,₹159,₹145,9% Off,( 972 ),NaN
33,"Biodance Bio-Collagen Real Deep Mask, Korean A...",₹1600,₹1520,5% Off,( 15 ),NaN
34,BiE O2wow!- Oxygenating & Firming Mask,₹2199,₹1979,10% Off,( 209 ),NaN
35,LANEIGE Water Sleeping Mask,NaN,₹2240,NaN,( 32 ),NaN
36,Quench Snail Mucin Collagen Boost Mask,₹349,₹307,12% Off,( 274 ),NaN
37,Nykaa Lemon + Honey Sheet Mask For Glowing & C...,₹100,₹80,20% Off,( 7299318 ),https://images-static.nykaa.com/media/OnlyatNy...
38,MCaffeine D-Tan Removal Coffee Clay Face Mask ...,₹575,₹489,15% Off,( 14329 ),NaN
39,O3+ Facialist Mask,NaN,₹155,NaN,( 26950 ),NaN

# Toners

In [95]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #33
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/skin/toners-mists/c/8391?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [96]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,TONYMOLY Korean Wonder Ceramide Mochi Toner-Hy...,NaN,₹1500,NaN,( 74778 ),https://images-static.nykaa.com/media/catalog/...
1,Medicube PDRN Pink Cica Soothing Toner,NaN,₹2200,NaN,NaN,https://images-static.nykaa.com/media/catalog/...
2,"Plum 3% Niacinamide Toner With Rice Water, For...",₹440,₹409,7% Off,( 80910 ),https://images-static.nykaa.com/media/catalog/...
3,Cetaphil BHR Brightness Refresh Toner,₹1199,₹1079,10% Off,( 6459 ),https://images-static.nykaa.com/media/catalog/...
4,Lacto Calamine Rice Toner -Korean Skincare for...,₹219,₹199,9% Off,( 30 ),https://images-static.nykaa.com/media/catalog/...
5,Beauty Of Joseon Ginseng Essence Water,NaN,₹1570,NaN,( 4923 ),https://images-static.nykaa.com/media/catalog/...
6,Uriage Thermal Water Mineralized Face Toner Mi...,NaN,₹1200,NaN,( 1038 ),NaN
7,Mario Badescu Face Mist With Aloe- Chamomile &...,NaN,₹600,NaN,( 472 ),NaN
8,Nykaa Skin Rose Water Toner Mist with Hyaluron...,₹329,₹280,15% Off,( 138 ),NaN
9,Aestura Theracne365 Hydro Active Toner,NaN,₹2000,NaN,( 1 ),https://images-static.nykaa.com/media/OnlyatNy...
10,Dot & Key Watermelon Superglow Pore Tightening...,₹395,₹320,19% Off,( 12387 ),https://images-static.nykaa.com/media/bestof20...
11,Plum 3% Niacinamide Alcohol-Free Toner With Ri...,₹440,₹409,7% Off,( 80865 ),https://images-static.nykaa.com/media/bestof20...
12,The Ordinary Glycolic Acid 7% Exfoliating Solu...,NaN,₹1275,NaN,( 65718 ),https://images-static.nykaa.com/media/bestof20...
13,SKIN1004 Madagascar Centella Tone Brightening ...,₹999,₹949,5% Off,( 1561 ),https://images-static.nykaa.com/media/bestof20...
14,d'you Inbalance Soothing Milky Toner - Hydrate...,NaN,₹2100,NaN,( 23 ),NaN
15,TONYMOLY Korean Wonder Rice Smoothing Toner-Hy...,NaN,₹1550,NaN,( 74696 ),https://images-static.nykaa.com/media/Ontheris...
16,LANEIGE Cream Skin Cerapeptide Toner & Moistur...,NaN,₹900,NaN,( 25764 ),https://images-static.nykaa.com/media/bestof20...
17,Minimalist 8% Glycolic Acid Toner For Exfoliat...,NaN,₹499,NaN,( 12760 ),https://images-static.nykaa.com/media/bestof20...
18,Round Lab 1025 Dokdo Toner,₹1499,₹1274,15% Off,( 14 ),NaN
19,TONYMOLY Korean Wonder Ceramide Mochi Toner-Hy...,NaN,₹575,NaN,( 1239 ),https://images-static.nykaa.com/media/Ontheris...
20,Beauty of Joseon Ginseng Essence Water,NaN,₹1570,NaN,( 4923 ),https://images-static.nykaa.com/media/catalog/...
21,I'm From Rice Toner,₹1960,₹1764,10% Off,( 1249 ),https://images-static.nykaa.com/media/catalog/...
22,Dot & Key Blueberry Hydrate Barrier Repair Mil...,₹449,₹377,16% Off,( 100 ),https://images-static.nykaa.com/media/catalog/...
23,Hyphen 7% Ceramides-NMF Face Toner Essence | 5...,₹495,₹470,5% Off,( 653 ),https://images-static.nykaa.com/media/catalog/...
24,The Face Shop Ceramide & Rice Face Toner - Kor...,NaN,₹899,NaN,( 6245 ),https://images-static.nykaa.com/media/catalog/...
25,Kama Ayurveda Pure Rose Water (Toner),NaN,₹1775,NaN,( 88242 ),https://images-static.nykaa.com/media/catalog/...
26,Khadi Natural Pure Rose Water Toner for Everyd...,₹249,₹187,25% Off,( 11268 ),NaN
27,COSRX AHA/BHA Clarifying Treatment Toner,₹1090,₹981,10% Off,( 5665 ),https://images-static.nykaa.com/media/bestof20...
28,PIXI Glow Tonic Exfoliating Toner With Glycoli...,NaN,₹1590,NaN,( 26577 ),https://images-static.nykaa.com/media/bestof20...
29,SKIN1004 Madagascar Centella Serum,₹999,₹949,5% Off,( 318 ),NaN
30,Dot & Key Blueberry Hydrate Barrier Repair Ton...,₹395,₹320,19% Off,( 6562 ),NaN
31,Paula's Choice Skin Perfecting 2% Bha Liquid E...,NaN,₹1200,NaN,( 80 ),https://images-static.nykaa.com/media/Ontheris...
32,Plum Bulgarian Valley Rose Water Alcohol-Free ...,₹360,₹324,10% Off,( 39988 ),NaN
33,Beauty of Joseon Glow Replenishing Rice Milk,NaN,₹1570,NaN,( 61 ),NaN
34,Mamaearth Rice Water Dewy Face Toner with 4% N...,₹429,₹395,8% Off,( 402 ),NaN
35,Plum Green Tea Alcohol-Free Face Toner,₹420,₹378,10% Off,( 78898 ),https://images-static.nykaa.com/media/bestof20...
36,Minimalist 3% Polyhydroxy PHA Face Toner With ...,NaN,₹399,NaN,( 20725 ),https://images-static.nykaa.com/media/bestof20...
37,Forest Essentials Facial Tonic Mist Pure Rosew...,NaN,₹1350,NaN,( 14857 ),NaN
38,Forest Essentials Facial Tonic Mist with Pure ...,NaN,₹595,NaN,( 14857 ),NaN
39,LANEIGE Cream Skin Cerapeptide Toner & Moistur...,NaN,₹1600,NaN,( 542 ),NaN

# Body Care

In [97]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #45
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/skin/body-care/c/8417?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [98]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,Orimii Bump Hydrating Body Butter for Reducing...,₹695,₹660,5% Off,( 96 ),https://images-static.nykaa.com/media/catalog/...
1,Cetaphil Moisturising Cream,₹899,₹746,17% Off,( 146238 ),https://images-static.nykaa.com/media/catalog/...
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,₹430,₹409,5% Off,( 41480 ),https://images-static.nykaa.com/media/catalog/...
3,Cetaphil Moisturising Lotion,₹789,₹655,17% Off,( 193928 ),https://images-static.nykaa.com/media/catalog/...
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,₹499,₹399,20% Off,( 6701 ),https://images-static.nykaa.com/media/catalog/...
5,Nivea Nourishing Body Milk,₹760,₹456,40% Off,( 294337 ),https://images-static.nykaa.com/media/catalog/...
6,CeraVe Foaming Cleanser Face Wash For Oily Ski...,₹520,₹494,5% Off,( 20012 ),https://images-static.nykaa.com/media/bestof20...
7,"CeraVe Moisturizer For Dry Skin, Barrier Repai...",₹1690,₹1606,5% Off,( 8560 ),NaN
8,"Vit C Body Oil for Brightening, Dryness, Uneve...",NaN,₹1350,NaN,( 62 ),NaN
9,Plum BodyLovin Vanilla Caramello Bestselling B...,₹475,₹404,15% Off,( 28492 ),https://images-static.nykaa.com/media/bestof20...
10,CeraVe Moisturizing Body Lotion for Normal to ...,₹1750,₹1663,5% Off,( 12580 ),https://images-static.nykaa.com/media/Editor_P...
11,Plum BodyLovin Vanilla Caramello Bestselling B...,₹475,₹404,15% Off,( 28492 ),https://images-static.nykaa.com/media/bestof20...
12,Hibiscus Monkey Limited Edition Velvet Spray S...,₹1120,₹1064,5% Off,( 11 ),NaN
13,Re'equil Ceramide & Hyaluronic Acid Moisturise...,₹295,₹280,5% Off,( 27908 ),https://images-static.nykaa.com/media/Editor_P...
14,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,₹499,₹399,20% Off,( 19163 ),https://images-static.nykaa.com/media/Editor_P...
15,Nykaa Wanderlust Dreaming of Paris Perfume Bod...,₹550,₹468,15% Off,( 500470 ),https://images-static.nykaa.com/media/bestof20...
16,mCaffeine 11% AHA BHA Strawberry Body Lotion f...,₹499,₹424,15% Off,( 18 ),NaN
17,Vaseline Intensive Care Deep Moisture Body Lotion,₹750,₹600,20% Off,( 148858 ),https://images-static.nykaa.com/media/Editor_P...
18,Plum BodyLovin Vanilla Vibes Body Oil,₹299,₹254,15% Off,( 38765 ),https://images-static.nykaa.com/media/bestof20...
19,Dove Deep Moisture Body Wash,₹560,₹420,25% Off,( 29578 ),https://images-static.nykaa.com/media/bestof20...
20,Forest Essentials After Bath Oil Oudh & Green ...,NaN,₹1850,NaN,( 288 ),https://images-static.nykaa.com/media/catalog/...
21,"Vaseline Cocoa Glow Serum In Lotion, 600 ml , ...",₹825,₹619,25% Off,( 123130 ),https://images-static.nykaa.com/media/catalog/...
22,Aveeno Daily Moisturising Lotion - Natural Oat...,₹1260,₹1135,10% Off,( 21322 ),https://images-static.nykaa.com/media/catalog/...
23,Cetaphil Baby Daily Lotion With Shea Butter Vi...,₹950,₹884,7% Off,( 5279 ),https://images-static.nykaa.com/media/catalog/...
24,Fixderma 2% Salicylic Acid + 2% Azelaic Acid S...,NaN,₹845,NaN,( 192 ),https://images-static.nykaa.com/media/catalog/...
25,NIVEA Cell Repair 50X Vit C Sunscreen Natural ...,₹645,₹387,40% Off,( 133198 ),https://images-static.nykaa.com/media/catalog/...
26,NIVEA 48H Deep Moisture Care Cocoa Butter & Vi...,₹565,₹339,40% Off,( 37941 ),https://images-static.nykaa.com/media/Editor_P...
27,Be Bodywise 5% Lactic Acid Body Lotion - For 2...,₹449,₹359,20% Off,( 4672 ),https://images-static.nykaa.com/media/Editor_P...
28,Nat Habit Pure Almond Baby Oil,₹1248,₹998,20% Off,( 213 ),NaN
29,Be Bodywise Pigmentation Removal Cream With 2....,₹599,₹549,8% Off,( 3558 ),https://images-static.nykaa.com/media/bestof20...
30,Cetaphil Gentle Cleansing & Moisturizing Combo,₹1358,₹1249,8% Off,( 381416 ),NaN
31,Venusia Max Intensive Moisturizing Lotion Norm...,₹1371,₹1124,18% Off,( 550 ),https://images-static.nykaa.com/media/Editor_P...
32,Forest Essentials Hydrating Facial Moisturiser...,NaN,₹1695,NaN,( 1980 ),NaN
33,Vaseline Healthy White Lightening Body Lotion,₹565,₹452,20% Off,( 93563 ),NaN
34,Chemist at Play Exfoliating Natural AHAs Body ...,₹349,₹290,17% Off,( 2637 ),https://images-static.nykaa.com/media/Editor_P...
35,Ponds Light Moisturiser Non-Oily Fresh Feel Wi...,₹715,₹501,30% Off,( 268741 ),NaN
36,Dermafique Intensive Restore Body Lotion Serum...,₹699,₹489,30% Off,( 1324 ),https://images-static.nykaa.com/media/Editor_P...
37,Neutriderm Moisturising Face & Body Lotion For...,NaN,₹1000,NaN,( 1757 ),https://images-static.nykaa.com/media/Editor_P...
38,Victoria's Secret Bare Vanilla Fragrance Lotion,₹2499,₹1999,20% Off,( 875 ),NaN
39,FoxTale Hula Hoop Brightening Body Wash by Fox...,₹399,₹327,18% Off,( 1846 ),https://images-static.nykaa.com/media/Editor_P...

In [1]:
import pandas as pd 
df = pd.read_csv("Face_Products.csv")
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,M.A.C Studio Fix Powder Plus 24-Hour Oil Contr...,NaN,₹3400,NaN,( 763194 ),https://images-static.nykaa.com/media/catalog/...,face_products
1,L'Oreal Paris Infallible 3-Second Setting Spra...,NaN,₹799,NaN,( 1143 ),https://images-static.nykaa.com/media/catalog/...,face_products
2,Maybelline New York Instant Age Rewind Eraser ...,₹799,₹639,20% Off,( 936280 ),https://images-static.nykaa.com/media/catalog/...,face_products
3,Kay Beauty Hydrating Foundation,₹1350,₹1080,20% Off,( 472860 ),https://images-static.nykaa.com/media/catalog/...,face_products
4,Kay Beauty Hyper Gloss Liquid Luminizing Highl...,NaN,₹949,NaN,( 2283 ),https://images-static.nykaa.com/media/catalog/...,face_products
...,...,...,...,...,...,...,...
2994,IDUN Minerals Liquid Minerals Foundation Nordi...,NaN,₹3300,NaN,NaN,NaN,face_products
2995,IDUN Minerals Matte Mineral Bronzer - Sommardrom,NaN,₹2800,NaN,NaN,NaN,face_products
2996,IDUN Minerals Cheek Blush Powder - Akerbar,NaN,₹2800,NaN,NaN,NaN,face_products
2997,IDUN Minerals Liquid Mineral Norrsken Foundation,NaN,₹3300,NaN,( 1 ),NaN,face_products
2998,IDUN Minerals Face Primer - Iris,NaN,₹2800,NaN,( 1 ),NaN,face_products

# Lip Care

In [2]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #32 pages # 627 products
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/skin/lip-care/c/8408?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [3]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,inde wild Dewy Lip Treatment Mini'S Kit,NaN,₹999,NaN,( 7 ),https://images-static.nykaa.com/media/catalog/...
1,LANEIGE Lip Glowy Balm,NaN,₹750,NaN,( 155085 ),https://images-static.nykaa.com/media/catalog/...
2,Wishcare Tinted Ceramide Lip Balm with SPF50 P...,₹299,₹248,17% Off,( 17706 ),https://images-static.nykaa.com/media/catalog/...
3,LANEIGE Lip Sleeping Mask Berry,NaN,₹600,NaN,( 99937 ),https://images-static.nykaa.com/media/catalog/...
4,Wishcare Ceramide Lip Balm With SPF 50 PA+++ K...,₹299,₹248,17% Off,( 6980 ),https://images-static.nykaa.com/media/catalog/...
5,LANEIGE Glaze Craze Tinted Lip Serum,NaN,₹1150,NaN,( 1263 ),https://images-static.nykaa.com/media/catalog/...
6,Dot & Key Meltie Lip Balm SPF 50+ PA+++,₹249,₹229,8% Off,( 1698 ),NaN
7,Vaseline Lip Tins,₹295,₹266,10% Off,( 61657 ),https://images-static.nykaa.com/media/Editor_P...
8,The Derma Co 1% Kojic Acid Lip Balm SPF 50 PA+++,₹349,₹314,10% Off,( 14 ),NaN
9,Dot & Key Barrier Repair Hydrating Lip Balm SP...,₹249,₹199,20% Off,( 5452 ),https://images-static.nykaa.com/media/Editor_P...
10,inde wild Dewy Lip Balms,₹799,₹759,5% Off,( 2043 ),https://images-static.nykaa.com/media/Editor_P...
11,"Hyphen Tinted Lip Balm - Hazel, 1% Vit E, 2% S...",₹399,₹379,5% Off,( 2812 ),https://images-static.nykaa.com/media/bestof20...
12,Hyphen 2% Kojic Acid Spf 30 Lip Balm With Vita...,₹399,₹379,5% Off,( 4111 ),NaN
13,Swiss Beauty Kiss Kandy Lip Balm,NaN,₹119,NaN,( 10517 ),NaN
14,"Foxtale Brightening Lip Balm With Peptides, Vi...",₹275,₹220,20% Off,( 2188 ),https://images-static.nykaa.com/media/bestof20...
15,DOT & KEY GLOSS BOSS LIP BALM VITAMIN C + E SP...,₹249,₹199,20% Off,( 50945 ),https://images-static.nykaa.com/media/Editor_P...
16,Lancome Lip Idole Butterglow Hydrating Lip Balm,NaN,₹3500,NaN,( 12 ),https://images-static.nykaa.com/media/Mostgift...
17,Typsy Beauty Glaze Pout Polish Peptide Lip Tre...,₹699,₹629,10% Off,( 288 ),NaN
18,Minimalist 8% L-Ascorbic Acid Lip Treatment Balm,NaN,₹399,NaN,( 8990 ),https://images-static.nykaa.com/media/Editor_P...
19,"Deconstruct Brightening Lip Balm SPF 50, Moist...",₹199,₹193,3% Off,( 8291 ),https://images-static.nykaa.com/media/bestof20...
20,Earth Rhythm Honey Lip Balm Spf 50 Brightens L...,NaN,₹375,NaN,( 72 ),https://images-static.nykaa.com/media/catalog/...
21,NIVEA Tinted Lip Balm With Natural Oils & 24H ...,₹260,₹156,40% Off,( 273548 ),https://images-static.nykaa.com/media/catalog/...
22,DIOR Addict Lip Glow,NaN,₹4400,NaN,( 1239 ),https://images-static.nykaa.com/media/catalog/...
23,STAZE 9To9 Y.U.M.M.Y Lip Gloss Balm,₹399,₹319,20% Off,( 408 ),https://images-static.nykaa.com/media/catalog/...
24,Uriage Xemose Lip Balm Shea Butter Vitamin C D...,NaN,₹800,NaN,( 184 ),https://images-static.nykaa.com/media/catalog/...
25,Chemist At Play Lip Balm SPF 50 Brightens & Re...,₹299,₹248,17% Off,( 288 ),https://images-static.nykaa.com/media/catalog/...
26,Dot & Key Ceramide & Peptide Barrier Repair SP...,₹249,₹199,20% Off,( 8808 ),NaN
27,Nykaa Cosmetics Lip Crush Macaron Lip Balm,₹299,₹239,20% Off,( 81076 ),NaN
28,The Derma Co 1% Kojic Acid Lip Balm with SPF 3...,₹329,₹296,10% Off,( 5337 ),https://images-static.nykaa.com/media/Editor_P...
29,LANEIGE Lip Sleeping Mask Ex Gummybear,NaN,₹600,NaN,( 1585 ),NaN
30,"Sebamed Lip Defense, For Dry And Chapped Lips,...",NaN,₹520,NaN,( 9137 ),https://images-static.nykaa.com/media/Editor_P...
31,SUGAR Tipsy Lips Moisturizing Balm,₹199,₹165,17% Off,( 22305 ),https://images-static.nykaa.com/media/Editor_P...
32,e.l.f. Cosmetics Squeeze Me Lip Balm,NaN,₹700,NaN,( 156 ),NaN
33,Nykaa Serial Kisser Moisturising Lip Balm With...,₹149,₹112,25% Off,( 182313 ),NaN
34,"Hyphen Tinted Lip Balm - Marshmallow, 1% Vit E...",₹399,₹379,5% Off,( 1761 ),https://images-static.nykaa.com/media/bestof20...
35,NYX Professional Makeup Smushy Matte Lip Balm,NaN,₹899,NaN,( 38 ),NaN
36,Aravi Organic Beetroot Tinted Lip Balm SPF 50 ...,₹279,₹209,25% Off,( 788 ),NaN
37,Minimalist SPF 30 Lip Balm,NaN,₹299,NaN,( 7639 ),https://images-static.nykaa.com/media/Editor_P...
38,SUGAR POP Nourishing Lip Balm,₹149,₹130,13% Off,( 26422 ),https://images-static.nykaa.com/media/Editor_P...
39,"Hyphen Tinted Lip Balm, Brightens Dark & Dry L...",₹399,₹379,5% Off,( 85 ),NaN

# Sun Care

In [4]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #52 pages # 1031 products
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/skin/sun-care/c/8428?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [5]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,"Hyphen All I Need Sunscreen SPF50 PA++++, Mois...",₹449,₹382,15% Off,( 4353 ),https://images-static.nykaa.com/media/catalog/...
1,Beauty of Joseon Relief Sun Aqua-Fresh Add SPF...,NaN,₹1570,NaN,( 528 ),https://images-static.nykaa.com/media/catalog/...
2,Foxtale Glow Sunscreen SPF 50 PA++++ with Vita...,₹349,₹276,21% Off,( 23618 ),https://images-static.nykaa.com/media/catalog/...
3,Aestura Derma UV365 Barrier Hydro Mineral Suns...,NaN,₹1500,NaN,( 14 ),https://images-static.nykaa.com/media/catalog/...
4,Wishcare Niacinamide Oil-Balance Sunscreen SPF...,₹499,₹394,21% Off,( 4509 ),https://images-static.nykaa.com/media/catalog/...
5,Plum 2% Niacinamide & Rice Water SPF 50 PA+++ ...,₹399,₹339,15% Off,( 44475 ),https://images-static.nykaa.com/media/catalog/...
6,"Deconstruct Gel Sunscreen SPF 50+ PA+++, No Wh...",₹349,₹332,5% Off,( 37020 ),https://images-static.nykaa.com/media/Editor_P...
7,Estee Lauder Sunscreen - Perfectionist Pro Mul...,NaN,₹4000,NaN,( 356 ),https://images-static.nykaa.com/media/Editor_P...
8,Forest Essentials Sheer Sun Fluid Sunscreen SP...,NaN,₹1575,NaN,( 1822 ),https://images-static.nykaa.com/media/Editor_P...
9,Simple Mattifying UV Fluid SPF 50 PA++++ with ...,₹499,₹449,10% Off,( 99 ),NaN
10,Dr. Sheth'S Ceramide & Vitamin C Sunscreen Spf...,₹499,₹374,25% Off,( 118895 ),https://images-static.nykaa.com/media/Editor_P...
11,Dot & Key Strawberry Dew Tinted Sunscreen SPF ...,₹549,₹489,11% Off,( 9506 ),https://images-static.nykaa.com/media/Editor_P...
12,Dot & Key Vitamin C + E Super Bright Sunscreen...,₹445,₹387,13% Off,( 125522 ),https://images-static.nykaa.com/media/bestof20...
13,Beauty of Joseon Relief Sunscreen Rice + Probi...,NaN,₹1570,NaN,( 11879 ),https://images-static.nykaa.com/media/Editor_P...
14,The Derma Co 1% Hyaluronic Sunscreen Spf 50 Pa...,₹499,₹424,15% Off,( 161357 ),https://images-static.nykaa.com/media/Editor_P...
15,Minimalist SPF 50 PA ++++ Sunscreen With Multi...,NaN,₹399,NaN,( 132187 ),https://images-static.nykaa.com/media/bestof20...
16,Beauty of Joseon Relief Sun Aqua-Fresh Add SPF...,NaN,₹1570,NaN,( 528 ),https://images-static.nykaa.com/media/bestof20...
17,"Dot & Key Watermelon Cooling Sunscreen, SPF 50...",₹445,₹387,13% Off,( 76371 ),https://images-static.nykaa.com/media/bestof20...
18,Aqualogica Glow+ Dewy Sunscreen Gel SPF 50+ PA...,₹449,₹359,20% Off,( 187256 ),https://images-static.nykaa.com/media/Editor_P...
19,Neutrogena Ultrasheer SPF50+ PA++++ Ultra Ligh...,₹780,₹577,26% Off,( 313917 ),https://images-static.nykaa.com/media/Editor_P...
20,Cetaphil Sun SPF 50+ Light Gel Very High Prote...,₹1299,₹1169,10% Off,( 11297 ),https://images-static.nykaa.com/media/catalog/...
21,"Deconstruct Gel Sunscreen SPF 50+ PA+++, No Wh...",₹349,₹332,5% Off,( 37020 ),https://images-static.nykaa.com/media/catalog/...
22,Conscious Chemist Niacinamide Sunscreen SPF 50...,₹499,₹324,35% Off,( 4204 ),https://images-static.nykaa.com/media/catalog/...
23,Dot & Key Blueberry Hydrate Barrier Repair Sun...,₹445,₹387,13% Off,( 18879 ),https://images-static.nykaa.com/media/catalog/...
24,ISDIN Fotoprotector Fusion Water Magic SPF 50 ...,NaN,₹2850,NaN,( 6143 ),https://images-static.nykaa.com/media/catalog/...
25,Wishcare Sunscreen Body Lotion SPF 50 Broad Sp...,₹499,₹394,21% Off,( 19168 ),https://images-static.nykaa.com/media/catalog/...
26,Fixderma Shadow Sunscreen SPF 50+ Gel For Oily...,₹640,₹576,10% Off,( 15037 ),https://images-static.nykaa.com/media/Editor_P...
27,Minimalist Light Fluid SPF 50 Face Sunscreen,NaN,₹499,NaN,( 5332 ),https://images-static.nykaa.com/media/bestof20...
28,La Roche-Posay Anthelios UVMUNE400 Invisible F...,NaN,₹1400,NaN,( 169 ),https://images-static.nykaa.com/media/OnlyatNy...
29,Re'equil Ultra Matte Dry Touch Sunscreen SPF 5...,₹645,₹613,5% Off,( 52954 ),https://images-static.nykaa.com/media/Editor_P...
30,Eucerin Hydro Protect Ultra-Light Sunscreen Fl...,₹1305,₹1175,10% Off,( 57 ),https://images-static.nykaa.com/media/OnlyatNy...
31,Forest Essentials Soundarya Radiance Cream Wit...,NaN,₹6850,NaN,( 3412 ),NaN
32,Episoft AC Moisturiser SPF 30 With Microencaps...,₹678,₹610,10% Off,( 19604 ),https://images-static.nykaa.com/media/Editor_P...
33,Dot & Key Cica Calming Mattifying Sunscreen In...,₹445,₹387,13% Off,( 21314 ),NaN
34,Aqualogica Radiance+ SPF 50+ PA++++,₹449,₹359,20% Off,( 98221 ),NaN
35,Dot & Key CSMS Vitamin C Bestseller Combo,₹1734,₹1387,20% Off,( 314309 ),NaN
36,"Bioderma Moisturizer Sebium Hydra for Oily, Ac...",NaN,₹1195,NaN,( 3124 ),https://images-static.nykaa.com/media/Editor_P...
37,Eclipse Solaire Active Sunscreen SPF 50 PA+++ ...,NaN,₹850,NaN,( 508 ),NaN
38,Beauty Of Joseon Matte Sunscreen Stick Mugwort...,NaN,₹1570,NaN,( 922 ),NaN
39,Foxtale Dewy Sunscreen SPF 70 PA++++ With Niac...,₹495,₹396,20% Off,( 15788 ),https://images-static.nykaa.com/media/Editor_P...

# Hair Care

In [6]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #204 pages 4073 products
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/hair-care/hair/c/25?page_no={i}&sort=popularity&root=nav_2&dir=desc&order=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [7]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,Olaplex No. 5 Bond Maintenance Conditioner,NaN,₹3200,NaN,( 2934 ),https://images-static.nykaa.com/media/catalog/...
1,Wishcare Hair Growth Serum Concentrate|In-Vivo...,₹999,₹699,30% Off,( 31397 ),https://images-static.nykaa.com/media/catalog/...
2,L'Oréal Professionnel Absolut Repair Mask For ...,NaN,₹990,NaN,( 35624 ),https://images-static.nykaa.com/media/catalog/...
3,"L'Oreal Paris Extraordinary Oil Hair Serum, An...",₹729,₹620,15% Off,( 254872 ),https://images-static.nykaa.com/media/catalog/...
4,Tresemme Keratin Smooth With Argan Oil Shampoo,₹865,₹606,30% Off,( 504320 ),https://images-static.nykaa.com/media/catalog/...
5,L'Oréal Professionnel Absolut Repair Shampoo F...,NaN,₹750,NaN,( 37580 ),https://images-static.nykaa.com/media/catalog/...
6,The Ordinary Multi-Peptide Serum for Hair Dens...,₹2150,₹1800,16% Off,( 24556 ),https://images-static.nykaa.com/media/Editor_P...
7,Be Bodywise Hair Growth Serum Roll On - 3% Ros...,NaN,₹599,NaN,( 10916 ),https://images-static.nykaa.com/media/bestof20...
8,Redken Acidic Bonding Concentrate Leave-In Tre...,NaN,₹2000,NaN,( 1195 ),https://images-static.nykaa.com/media/Editor_P...
9,L'Oreal Paris Hyaluron Moisture Anti-frizz Sha...,₹1315,₹921,30% Off,( 44563 ),https://images-static.nykaa.com/media/bestof20...
10,"inde wild Champi Hair Oil With Bhringraj, Brah...",₹844,₹802,5% Off,( 5655 ),https://images-static.nykaa.com/media/Editor_P...
11,Olaplex No. 4 Bond Maintenance Shampoo,NaN,₹2950,NaN,( 3854 ),https://images-static.nykaa.com/media/Editor_P...
12,L'Oreal Professionnel Vitamino Color Spectrum ...,NaN,₹1600,NaN,( 16 ),NaN
13,L'Oreal Professionnel Absolut Repair Shampoo &...,₹1740,₹1566,10% Off,( 146484 ),https://images-static.nykaa.com/media/bestof20...
14,Love Beauty & Planet Argan Oil And Lavender Su...,₹658,₹494,25% Off,( 89801 ),https://images-static.nykaa.com/media/Editor_P...
15,L'Oreal Professionnel Xtenso Care Sulfate-Free...,NaN,₹1290,NaN,( 16534 ),https://images-static.nykaa.com/media/Editor_P...
16,"L'Oreal Professionnel Absolut Repair Shampoo, ...",₹3130,₹2817,10% Off,( 162349 ),NaN
17,L'Oreal Paris Hyaluron Moisture Anti-frizz Con...,₹599,₹509,15% Off,( 87659 ),https://images-static.nykaa.com/media/bestof20...
18,Dove 10 In 1 Deep Repair Treatment Hair Mask F...,₹649,₹487,25% Off,( 35964 ),https://images-static.nykaa.com/media/bestof20...
19,L’Oréal Paris Hyaluron Pure 72H Purifying Sham...,₹1315,₹921,30% Off,( 2441 ),https://images-static.nykaa.com/media/bestof20...
20,Kerastase Genesis Anti-Hair Fall Daily Scalp S...,NaN,₹5100,NaN,( 140 ),https://images-static.nykaa.com/media/catalog/...
21,Bare Anatomy Anti-Dandruff Shampoo with Salicy...,₹484,₹479,1% Off,( 15490 ),https://images-static.nykaa.com/media/catalog/...
22,L'Oreal Professionnel Xtenso Care Sulfate-Free...,NaN,₹1045,NaN,( 17353 ),https://images-static.nykaa.com/media/catalog/...
23,L'Oreal Paris Glycolic Gloss Shine Boosting Sh...,₹1315,₹921,30% Off,( 656 ),https://images-static.nykaa.com/media/catalog/...
24,Kerastase Genesis Conditioner For Fine To Medi...,NaN,₹3400,NaN,( 32 ),https://images-static.nykaa.com/media/catalog/...
25,Wishcare Hair Growth Serum Concentrate|In-Vivo...,₹2349,₹1997,15% Off,( 62894 ),https://images-static.nykaa.com/media/catalog/...
26,Nexxus Promend Oil Resurrection Hair Serum,₹2499,₹2374,5% Off,( 869 ),https://images-static.nykaa.com/media/bestof20...
27,Pilgrim 3% Redensyl & 4% Anagain Advance Hair ...,₹995,₹876,12% Off,( 34896 ),https://images-static.nykaa.com/media/Editor_P...
28,L'Oreal Professionnel Absolut Repair Molecular...,NaN,₹1600,NaN,( 725 ),NaN
29,WishCare Multi Peptide Anti Hairfall Shampoo -...,₹499,₹399,20% Off,( 2920 ),https://images-static.nykaa.com/media/Editor_P...
30,Love Beauty & Planet Argan Oil & Lavender Hair...,₹600,₹480,20% Off,( 33381 ),https://images-static.nykaa.com/media/Editor_P...
31,Olaplex No. 7 Bonding Frizz Reduction & Heat P...,₹3300,₹2950,11% Off,( 1722 ),https://images-static.nykaa.com/media/bestof20...
32,L'Oreal Professionnel Vitamino Color Mask for ...,NaN,₹990,NaN,( 8158 ),https://images-static.nykaa.com/media/Editor_P...
33,L'Oreal Professionnel Absolut Repair 10-in-1 M...,NaN,₹1390,NaN,( 7954 ),https://images-static.nykaa.com/media/bestof20...
34,Matrix Mega Smooth Professional Shampoo For Fr...,NaN,₹385,NaN,( 73594 ),https://images-static.nykaa.com/media/Editor_P...
35,Love Beauty & Planet Argan Oil And Lavender Su...,₹785,₹589,25% Off,( 48557 ),https://images-static.nykaa.com/media/Editor_P...
36,L'Oreal Professionnel Aminexil Advanced Anti-H...,₹3150,₹2898,8% Off,( 618 ),https://images-static.nykaa.com/media/Editor_P...
37,Biolage Smoothproof Professional 6-in-1 Deep S...,NaN,₹350,NaN,( 37718 ),https://images-static.nykaa.com/media/Editor_P...
38,Brillare 20% Rosemary Oil Shots with 10% Olive...,₹795,₹716,10% Off,( 1726 ),NaN
39,L'Oreal Professionnel Xtenso Care Sulfate Free...,₹2335,₹2102,10% Off,( 67816 ),https://images-static.nykaa.com/media/bestof20...

# Hair Tools and Accessories

In [8]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #122
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/hair-care/tools-and-accessories/c/219?page_no={i}&sort=popularity&ptype=lst&id=219&root=nav_2&dir=desc&order=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [9]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,GHD The Dresser Oval Dressing Hair Brush,NaN,₹3000,NaN,NaN,https://images-static.nykaa.com/media/catalog/...
1,UrbanYog MakeMeeBold Hair Dryer and Volumizer ...,₹6999,₹2520,64% Off,( 372 ),https://images-static.nykaa.com/media/catalog/...
2,"AGARO HV2179 1200W Volumizer Hair Dryer, 24K G...",₹3999,₹2199,45% Off,( 6205 ),https://images-static.nykaa.com/media/catalog/...
3,Philips Hair Straightener Brush | Naturally St...,₹3995,₹2900,27% Off,( 3932 ),https://images-static.nykaa.com/media/catalog/...
4,Winston Rechargeable 2-in-1 Face and Eyebrow T...,₹2990,₹1749,42% Off,( 286 ),https://images-static.nykaa.com/media/catalog/...
5,"Nykaa Anti-Acne Face Wash With Salicylic Acid,...",₹279,₹237,15% Off,( 872609 ),https://images-static.nykaa.com/media/catalog/...
6,Ikonic Professional Pro Titanium Shine 3.0,₹8500,₹6120,28% Off,( 2690 ),NaN
7,Ikonic Professional Simply Straight( Black),₹2650,₹1908,28% Off,( 3593 ),NaN
8,Tangle Teezer Wet Detangler Hairbrush for Deta...,NaN,₹1750,NaN,( 1519 ),NaN
9,Ikonic Me 3 In 1 Express Styler - Pink,₹3350,₹2144,36% Off,( 1461 ),NaN
10,Ikonic Professional Blaze Hair Dryer Black,₹2575,₹1854,28% Off,( 3224 ),NaN
11,Ikonic Professional Curling Tong CT-22 Black 2.0,₹4450,₹3204,28% Off,( 1528 ),NaN
12,GHD The Blow Dryer 25mm Ceramic Radial Hair Br...,NaN,₹2500,NaN,NaN,https://images-static.nykaa.com/media/Ontheris...
13,Ikonic Professional Curling Tong CT-28 -2.0,₹4500,₹3240,28% Off,( 1683 ),NaN
14,Matra Silicone Hair Scalp Massager & Anti Dand...,₹159,₹99,38% Off,( 1849 ),NaN
15,Philips Kerashine Hair Straightener | Purple |...,₹2795,₹2599,7% Off,( 766 ),NaN
16,Tangle Teezer Wet Detangler Hairbrush for Deta...,NaN,₹1750,NaN,( 642 ),NaN
17,"AGARO HD-1211E Hair Dryer 1100W, Foldable Comp...",₹899,₹759,16% Off,( 2388 ),NaN
18,Ikonic Professional CRIMP & STYLE Crimper Purple,₹4000,₹2880,28% Off,( 1286 ),NaN
19,IkonicCurl me up-22mm-Purple,₹2750,₹1760,36% Off,( 315 ),NaN
20,Sanfe Stunner Microfiber Hair Wrap Towel,₹399,₹331,17% Off,( 256 ),https://images-static.nykaa.com/media/catalog/...
21,"AGARO HS1119 3-in-1 Hair Styler, Straightener,...",₹2199,₹1099,50% Off,( 501 ),https://images-static.nykaa.com/media/catalog/...
22,Ikonic Professional Slim Titanium Crimp 2.0,₹7000,₹5040,28% Off,( 929 ),https://images-static.nykaa.com/media/catalog/...
23,Alan Truman Mini Blow - Travel-size Blow Dryin...,₹2499,₹1999,20% Off,( 64 ),https://images-static.nykaa.com/media/catalog/...
24,GHD The Blow Dryer 55mm Ceramic Radial Hair Br...,NaN,₹3000,NaN,( 1 ),https://images-static.nykaa.com/media/catalog/...
25,Philips 1000W Compact Hair Dryer,NaN,₹1095,NaN,( 12360 ),https://images-static.nykaa.com/media/catalog/...
26,Ikonic Professional Slim Titanium Shine 3.0 Ha...,₹8000,₹5760,28% Off,( 546 ),NaN
27,Dyson Corrale Hair Straightener - Bright Copper,₹43900,₹29900,32% Off,( 53 ),https://images-static.nykaa.com/media/Mostgift...
28,VEGA Professional Pro Gold Ceramic Shine Hair ...,₹4199,₹3233,23% Off,( 8 ),NaN
29,Ikonic me 3in1 Express Styler - Grey,₹3350,₹2144,36% Off,( 1529 ),NaN
30,Ikonic Me-black Beauty Hair Iron,₹1850,₹1277,31% Off,( 1749 ),NaN
31,Alan Truman Automatic Split-ends Trimmer For D...,₹5999,₹4199,30% Off,( 1992 ),NaN
32,Nat Habit Oil Treated Kacchi Neem Handmade Woo...,₹705,₹494,30% Off,( 150 ),https://images-static.nykaa.com/media/Ontheris...
33,Tash Hair Twirl Automatic Cordless Hair Curler...,₹3799,₹3299,13% Off,( 99 ),NaN
34,Bronson Professional Volumizer Blow Hair Dryer...,₹2000,₹1400,30% Off,( 1137 ),NaN
35,Ikonic Professional Curling Tong CT-25 Black 2.0,₹4450,₹3204,28% Off,( 849 ),NaN
36,Tangle Teezer The Large Wet Detangler - Peach ...,NaN,₹2200,NaN,( 134 ),NaN
37,Fabskin Luxury Satin Silk Hair Bonnet Cap For ...,₹200,₹189,6% Off,( 218 ),NaN
38,Bronson Professional Wooden Scalp Massager Com...,₹325,₹245,25% Off,( 97 ),NaN
39,Nat Habit Oil Treated Kacchi Neem Ayurvedic Wo...,₹235,₹195,17% Off,( 8525 ),https://images-static.nykaa.com/media/Ontheris...

# Fragrance

# Female Fragrance

In [10]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #135
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/fragrance/women/c/54?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [11]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,Engage Yang Eau De Parfum For Women,₹649,₹487,25% Off,( 3692 ),https://images-static.nykaa.com/media/catalog/...
1,Nykaa Wanderlust Japanese Cherry Blossom Hydra...,₹599,₹539,10% Off,( 316074 ),https://images-static.nykaa.com/media/catalog/...
2,Lancome Idole Eau De Parfum Best Seller Luxury...,NaN,₹10500,NaN,( 1216 ),https://images-static.nykaa.com/media/catalog/...
3,Asaya Depigmentation Underarm Spray for Dark U...,₹499,₹449,10% Off,( 289 ),https://images-static.nykaa.com/media/catalog/...
4,Bath & Body Works Into The Night Fine Fragranc...,₹2299,₹1529,33% Off,( 431 ),https://images-static.nykaa.com/media/catalog/...
5,Yves Saint Laurent Libre Eau De Parfum With La...,NaN,₹10000,NaN,( 3886 ),https://images-static.nykaa.com/media/catalog/...
6,Nykaa Perfumes Gourmand Collection Day & Night...,NaN,₹899,NaN,( 478 ),NaN
7,Victoria's Secret Bare Vanilla Fragrance Mist,₹2699,₹2159,20% Off,( 215 ),https://images-static.nykaa.com/media/bestof20...
8,Bath & Body Works A Thousand Wishes Travel Siz...,₹1199,₹799,33% Off,( 235 ),https://images-static.nykaa.com/media/bestof20...
9,Burberry Goddess Eau De Parfum For Her,NaN,₹4995,NaN,( 1310 ),https://images-static.nykaa.com/media/bestof20...
10,Carolina Herrera Good Girl Eau De Parfum For Her,NaN,₹8700,NaN,( 6695 ),https://images-static.nykaa.com/media/bestof20...
11,Moi Amour Floral Travel Size Mini Perfume With...,NaN,₹249,NaN,( 624747 ),https://images-static.nykaa.com/media/Editor_P...
12,Ajmal Neea EDP Perfume For Women.,₹1000,₹500,50% Off,( 628 ),https://images-static.nykaa.com/media/bestof20...
13,Moi Joie De Vivre Citrus Fresh Perfume With Aq...,₹1800,₹1530,15% Off,( 56310 ),https://images-static.nykaa.com/media/Editor_P...
14,Plum BodyLovin Vanilla Vibes Body Mist For A L...,₹395,₹328,17% Off,( 57308 ),https://images-static.nykaa.com/media/Editor_P...
15,Victoria's Secret Pure Seduction Fragrance Mist,₹2699,₹2159,20% Off,( 105 ),NaN
16,Plum Bodylovin' Hazelnut Eclair Body Mist,₹395,₹324,18% Off,( 65 ),NaN
17,Nykaa Wanderlust Forbidden Garden EDP For Wome...,NaN,₹349,NaN,( 5633 ),https://images-static.nykaa.com/media/Editor_P...
18,Layer'r Wottagirl Vanilla Twist Fragrant Body ...,₹239,₹215,10% Off,( 22176 ),https://images-static.nykaa.com/media/Editor_P...
19,Moi Cherry Bomb Long-Lasting Eau De Parfum For...,NaN,₹899,NaN,( 478 ),NaN
20,Bella Vita Luxury Perfumes Gift Set For Women,₹849,₹549,35% Off,( 26126 ),https://images-static.nykaa.com/media/catalog/...
21,Plum Bodylovin' Vanilla Caramello Eau De Parfum,₹899,₹719,20% Off,( 5926 ),https://images-static.nykaa.com/media/catalog/...
22,Bath & Body Works A Thousand Wishes Fine Fragr...,₹2299,₹1529,33% Off,( 344 ),https://images-static.nykaa.com/media/catalog/...
23,Sol de Janeiro Cheirosa 62 Perfume Mist with V...,NaN,₹2715,NaN,( 3174 ),https://images-static.nykaa.com/media/catalog/...
24,Calvin Klein My Euphoria Eau De Parfum For Women,NaN,₹8100,NaN,( 45 ),https://images-static.nykaa.com/media/catalog/...
25,Lancome La Vie Est Belle Eau De Parfum,NaN,₹10500,NaN,( 671 ),https://images-static.nykaa.com/media/catalog/...
26,Clinique Happy Perfume Spray For Her,₹9999,₹4000,60% Off,( 2446 ),https://images-static.nykaa.com/media/Editor_P...
27,Carolina Herrera Good Girl Blush Eau De Parfum...,NaN,₹6600,NaN,( 105 ),https://images-static.nykaa.com/media/bestof20...
28,Bella Vita Organic Luxury Date Perfume For Her,₹999,₹549,45% Off,( 11152 ),https://images-static.nykaa.com/media/Editor_P...
29,Victoria's Secret Bombshell Fine Fragrance Mist,₹2999,₹2549,15% Off,( 30 ),NaN
30,Plum BodyLovin Vanilla Vibes Body Mist For A L...,₹395,₹328,17% Off,( 57308 ),https://images-static.nykaa.com/media/bestof20...
31,PRADA Paradoxe Intense EAU De Parfum For Her,NaN,₹14300,NaN,( 30 ),https://images-static.nykaa.com/media/bestof20...
32,Engage Femme Eau De Parfum For Women,₹649,₹487,25% Off,( 4429 ),NaN
33,Plum Body Lovin Vanilla Vibes Body Mist For A ...,₹550,₹440,20% Off,( 57308 ),https://images-static.nykaa.com/media/Editor_P...
34,"Moi Enchanted Bouquet Perfume With Peony, Stra...",₹649,₹584,10% Off,( 1267 ),https://images-static.nykaa.com/media/Mostgift...
35,Paco Rabanne Million Gold Eau De Parfum For Her,NaN,₹11410,NaN,( 27 ),https://images-static.nykaa.com/media/Mostgift...
36,Davidoff Cool Water Reborn Eau De Toilette For...,NaN,₹5750,NaN,( 50 ),https://images-static.nykaa.com/media/Mostgift...
37,Bath & Body Works In The Stars Fine Fragrance ...,₹2199,₹1463,33% Off,( 925 ),https://images-static.nykaa.com/media/Editor_P...
38,Estee Lauder Modern Muse Eau De Parfum For Her,₹11000,₹6600,40% Off,( 348 ),https://images-static.nykaa.com/media/Mostgift...
39,Tom Ford Ombre Leather Eau de Parfum For Him,₹3400,₹2600,24% Off,( 986 ),https://images-static.nykaa.com/media/Editor_P...

# Male Fragrance

In [12]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from bs4 import BeautifulSoup
import time
import os 
import requests
import numpy as np 
import pandas as pd 

name_data = []
review_data = []
price_data = []
discount_data = []
og_price_data = []
image_links = []

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"}
# Chrome options (helps avoid basic bot detection)
options = Options()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options)

for i in range(1,3): #98
    print(f"scraping page {i}")

    url = f"https://www.nykaa.com/fragrance/men/c/55?page_no={i}&sort=popularity"
    driver.get(url)
    time.sleep(2)

    soup = BeautifulSoup(driver.page_source,"html.parser") 

    containers = soup.find_all("div" , class_ = "productWrapper css-17nge1h")

    if not containers:
        print("NO Products found.")
        break


    for c in containers:

        name = c.find("div" , attrs = {"class" : "css-xrzmfa"})
        name_data.append(name.text.strip() if name else np.nan)

        review = c.find("span" , attrs = {"class" : "css-1qbvrhp"})
        review_data.append(review.text.strip() if review else np.nan)

        price = c.find("span" , attrs = {"class" : "css-111z9ua"})
        price_data.append(price.text.strip() if price else np.nan)

        discount = c.find("span" , attrs = {"class" : "css-cjd9an"})
        discount_data.append(discount.text.strip() if discount else np.nan)

        og_price = c.find("span" , attrs = {"class" : "css-17x46n5"})
        og_price_data.append(og_price.text.strip() if og_price else np.nan)

        
        img = c.find("img")
        if img:
            link = img.get("src") or img.get("data-src") or img.get("data-lazy")
            if link and link.startswith("/"):
                link = "https://www.nykaa.com/" + link
            image_links.append(link if link else np.nan)
        else:
            image_links.append(np.nan)


print("Scraping completed")

scraping page 1
scraping page 2
Scraping completed

In [13]:
import pandas as pd
df = pd.DataFrame({'Product Name': name_data,
                  'Original Price': og_price_data,
                  'Offer Price': price_data,
                  'Discount': discount_data,
                  'Reviews': review_data,
                  'Images Links': image_links})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links
0,DIOR Sauvage Eau De Parfum For Him,NaN,₹10700,NaN,( 1341 ),https://images-static.nykaa.com/media/catalog/...
1,Jean Paul Gaultier Le Male Eau De Parfum For Him,NaN,₹7330,NaN,( 676 ),https://images-static.nykaa.com/media/catalog/...
2,Yves Saint Laurent Y Eau De Parfum With Clean ...,NaN,₹12000,NaN,( 1658 ),https://images-static.nykaa.com/media/catalog/...
3,Clinique Happy For Men Cologne Spray,₹6000,₹2400,60% Off,( 1896 ),https://images-static.nykaa.com/media/catalog/...
4,Calvin Klein CK Be For Men Eau De Toilette,NaN,₹6295,NaN,( 493 ),https://images-static.nykaa.com/media/catalog/...
5,Giorgio Armani Acqua Di Gio Eau De Toilette Fo...,NaN,₹8200,NaN,( 1334 ),https://images-static.nykaa.com/media/catalog/...
6,Jaguar Classic Black Eau De Toilette For Him,₹3600,₹2880,20% Off,( 3671 ),https://images-static.nykaa.com/media/bestof20...
7,Jean Paul Gaultier Le Male Elixir Parfum For Him,NaN,₹8550,NaN,( 247 ),https://images-static.nykaa.com/media/bestof20...
8,DIOR Sauvage Eau De Toilette For Him,NaN,₹12400,NaN,( 584 ),https://images-static.nykaa.com/media/bestof20...
9,Davidoff Cool Water Eau De Toilette For Men,NaN,₹4995,NaN,( 1508 ),https://images-static.nykaa.com/media/bestof20...
10,Tom Ford Ombre Leather Eau de Parfum For Him,₹3400,₹2600,24% Off,( 986 ),https://images-static.nykaa.com/media/Editor_P...
11,Lattafa Khamrah Qahwa Long Lasting Eau De Parfum,₹5000,₹4000,20% Off,( 75 ),NaN
12,Burberry London For Men Eau De Toilette,NaN,₹6995,NaN,( 66 ),https://images-static.nykaa.com/media/bestof20...
13,Bella Vita Luxury Perfumes Gift Set For Men,₹849,₹549,35% Off,( 10116 ),https://images-static.nykaa.com/media/Mostgift...
14,Bella Vita Unisex Luxury Perfume Gift Set,₹849,₹549,35% Off,( 14017 ),https://images-static.nykaa.com/media/Mostgift...
15,Skinn By Titan Raw Perfume For Men EDP,₹695,₹591,15% Off,( 6758 ),NaN
16,Calvin Klein Ck Everyone Eau De Parfum For Him,NaN,₹5995,NaN,( 63 ),https://images-static.nykaa.com/media/Mostgift...
17,Paco Rabanne 1 Million Elixir Parfum Intense F...,NaN,₹11050,NaN,( 122 ),https://images-static.nykaa.com/media/Mostgift...
18,Lattafa Khamrah Long Lasting Unisex Eau De Parfum,NaN,₹5000,NaN,( 64 ),https://images-static.nykaa.com/media/bestof20...
19,DIOR Sauvage Elixir Spray For Him,NaN,₹17200,NaN,( 354 ),https://images-static.nykaa.com/media/Mostgift...
20,Contraband Hands Off Eau De Parfum,₹1750,₹1400,20% Off,( 226 ),https://images-static.nykaa.com/media/catalog/...
21,Yves Saint Laurent MYSLF Eau De Parfum For Him,NaN,₹13000,NaN,( 49 ),https://images-static.nykaa.com/media/catalog/...
22,Tom Ford Ombre Leather Parfum,NaN,₹15300,NaN,( 89 ),https://images-static.nykaa.com/media/catalog/...
23,Bella Vita White-Oud Eau De Perfume For Men & ...,₹999,₹549,45% Off,( 3515 ),https://images-static.nykaa.com/media/catalog/...
24,Burberry Hero Eau De Toilette For Men,NaN,₹9250,NaN,( 43 ),https://images-static.nykaa.com/media/catalog/...
25,BVLGARI Man In Black Eau De Parfum For Him,NaN,₹13500,NaN,( 414 ),https://images-static.nykaa.com/media/catalog/...
26,Paco Rabanne 1 Million Parfum For Men,NaN,₹10600,NaN,( 289 ),https://images-static.nykaa.com/media/Mostgift...
27,Bella Vita Honey Oud Unisex Eau De Perfume,₹999,₹549,45% Off,( 1960 ),https://images-static.nykaa.com/media/Editor_P...
28,Ajmal Ascend EDP Perfume For Women And Men,₹1000,₹500,50% Off,( 86 ),NaN
29,"Hermès Terre d'Hermès, Eau de Toilette",NaN,₹11000,NaN,( 77 ),https://images-static.nykaa.com/media/bestof20...
30,Tom Ford Black Orchid Eau de Parfum For Him,₹3200,₹2600,19% Off,( 668 ),https://images-static.nykaa.com/media/Mostgift...
31,Jaguar Classic Blue Eau De Toilette For Him,₹4100,₹2870,30% Off,( 560 ),https://images-static.nykaa.com/media/bestof20...
32,DIOR Homme Intense Eau De Parfum Intense For Him,NaN,₹14200,NaN,( 157 ),https://images-static.nykaa.com/media/Mostgift...
33,Nautica Voyage Eau De Toilette For Him,₹3900,₹2730,30% Off,( 126533 ),https://images-static.nykaa.com/media/bestof20...
34,Tom Ford Oud Wood Eau De Parfum,NaN,₹13900,NaN,( 6 ),https://images-static.nykaa.com/media/Mostgift...
35,DIOR Sauvage Parfum For Him,NaN,₹17800,NaN,( 115 ),https://images-static.nykaa.com/media/Mostgift...
36,Carolina Herrera Bad Boy Cobalt Eau De Parfum ...,NaN,₹7150,NaN,( 49 ),https://images-static.nykaa.com/media/Mostgift...
37,Ajmal India Oud Of Dubai Eau De Parfum,₹1099,₹901,18% Off,( 52 ),NaN
38,Azzaro The Most Wanted Intense Eau De Parfum F...,NaN,₹9800,NaN,( 204 ),https://images-static.nykaa.com/media/Mostgift...
39,PRADA Luna Rossa Black Eau De Parfum,NaN,₹9900,NaN,( 118 ),https://images-static.nykaa.com/media/Mostgift...

In [4]:
import pandas as pd

In [5]:
df1 = pd.read_csv("Body_Care.csv")
df2 = pd.read_csv("Cleansers.csv")
df3 = pd.read_csv("Eyes_Products.csv")
df4 = pd.read_csv("Face_Products.csv")
df5 = pd.read_csv("Female_Fragrance.csv")
df6 = pd.read_csv("Hair_Care.csv")
df7 = pd.read_csv("Hair_Tools_and_Accessories.csv")
df8 = pd.read_csv("Kits_and_Combos.csv")
df9 = pd.read_csv("Lip_Care.csv")
df10 = pd.read_csv("Lips_Products.csv")
df11 = pd.read_csv("Male_Fragrance.csv")
df12 = pd.read_csv("Masks.csv")
df13 = pd.read_csv("Moisturizers.csv")
df14 = pd.read_csv("Nail_Products.csv")
df15 = pd.read_csv("Serums.csv")
df16 = pd.read_csv("Sun_Care.csv")
df17 = pd.read_csv("Toners.csv")
df18 = pd.read_csv("Tools_and_Brushes.csv")

In [6]:
df = pd.concat([df1 , df2 , df3, df4 , df5 , df6 , df7 , df8 , df9 , df10 , df11, df12 ,df13 ,df14 ,df15 ,df16 ,df17 ,df18] ,ignore_index = True)

In [7]:
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,₹695,₹660,5% Off,( 96 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,₹899,₹746,17% Off,( 146238 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,₹430,₹409,5% Off,( 41480 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,₹789,₹655,17% Off,( 193928 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,₹499,₹399,20% Off,( 6701 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,₹1300,NaN,NaN,NaN,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,₹800,NaN,NaN,NaN,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,₹2900,NaN,NaN,NaN,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,₹1300,NaN,NaN,NaN,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,₹1300,NaN,NaN,NaN,Tools_and_Brushes

In [8]:
df.columns

Index(['Product Name', 'Original Price', 'Offer Price', 'Discount', 'Reviews',
       'Images Links', 'product_category'],
      dtype='object')

In [9]:
df["Offer Price"] = df["Offer Price"].str.replace("₹", "", regex=False)

In [10]:
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,₹695,660,5% Off,( 96 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,₹899,746,17% Off,( 146238 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,₹430,409,5% Off,( 41480 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,₹789,655,17% Off,( 193928 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,₹499,399,20% Off,( 6701 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,NaN,NaN,NaN,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,NaN,NaN,NaN,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes

In [11]:
df['Offer Price'] = pd.to_numeric(df['Offer Price'])

In [12]:
df.dtypes

Product Name        object
Original Price      object
Offer Price          int64
Discount            object
Reviews             object
Images Links        object
product_category    object
dtype: object

In [13]:
df.to_csv("Nyka.csv" , index = False)
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,₹695,660,5% Off,( 96 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,₹899,746,17% Off,( 146238 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,₹430,409,5% Off,( 41480 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,₹789,655,17% Off,( 193928 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,₹499,399,20% Off,( 6701 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,NaN,NaN,NaN,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,NaN,NaN,NaN,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes

In [14]:
df = pd.read_csv("Nyka.csv")
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,₹695,660,5% Off,( 96 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,₹899,746,17% Off,( 146238 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,₹430,409,5% Off,( 41480 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,₹789,655,17% Off,( 193928 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,₹499,399,20% Off,( 6701 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,NaN,NaN,NaN,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,NaN,NaN,NaN,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes

In [15]:
df["Original Price"] = df["Original Price"].str.replace("₹", "", regex=False)
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695,660,5% Off,( 96 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899,746,17% Off,( 146238 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430,409,5% Off,( 41480 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789,655,17% Off,( 193928 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499,399,20% Off,( 6701 ),https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,NaN,NaN,NaN,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,NaN,NaN,NaN,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes

In [16]:


df['Original Price'] = pd.to_numeric(df['Original Price'])

In [17]:
df.dtypes

Product Name         object
Original Price      float64
Offer Price           int64
Discount             object
Reviews              object
Images Links         object
product_category     object
dtype: object

In [18]:
df["Reviews"] = df["Reviews"].str.replace("(", "", regex=False)\
                     .str.replace(")", "", regex=False)

df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695.0,660,5% Off,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899.0,746,17% Off,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430.0,409,5% Off,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789.0,655,17% Off,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499.0,399,20% Off,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,NaN,NaN,NaN,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,NaN,NaN,NaN,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes

In [19]:
df['Reviews'] = pd.to_numeric(df['Reviews'])
df.dtypes

Product Name         object
Original Price      float64
Offer Price           int64
Discount             object
Reviews             float64
Images Links         object
product_category     object
dtype: object

In [20]:
df["Discount"] = df["Discount"].str.replace("Off", "", regex=False)
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695.0,660,5%,96.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899.0,746,17%,146238.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430.0,409,5%,41480.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789.0,655,17%,193928.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499.0,399,20%,6701.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,NaN,NaN,NaN,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,NaN,NaN,NaN,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,NaN,NaN,NaN,Tools_and_Brushes

In [21]:
df["Images Links"] = df["Images Links"].fillna(" Link Not Available")
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695.0,660,5%,96.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899.0,746,17%,146238.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430.0,409,5%,41480.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789.0,655,17%,193928.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499.0,399,20%,6701.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,NaN,NaN,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,NaN,NaN,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,NaN,NaN,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,NaN,NaN,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,NaN,NaN,Link Not Available,Tools_and_Brushes

In [22]:
df["Images Links"] = df["Images Links"].replace("Not Available", "Link Not Available")

In [23]:
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695.0,660,5%,96.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899.0,746,17%,146238.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430.0,409,5%,41480.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789.0,655,17%,193928.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499.0,399,20%,6701.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,NaN,NaN,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,NaN,NaN,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,NaN,NaN,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,NaN,NaN,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,NaN,NaN,Link Not Available,Tools_and_Brushes

In [24]:
df["Reviews"] = df["Reviews"].fillna(0)
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695.0,660,5%,96.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899.0,746,17%,146238.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430.0,409,5%,41480.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789.0,655,17%,193928.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499.0,399,20%,6701.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,NaN,0.0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,NaN,0.0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,NaN,0.0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,NaN,0.0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,NaN,0.0,Link Not Available,Tools_and_Brushes

In [25]:
df["Discount"] = df["Discount"].fillna("No Discount")
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695.0,660,5%,96.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899.0,746,17%,146238.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430.0,409,5%,41480.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789.0,655,17%,193928.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499.0,399,20%,6701.0,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,No Discount,0.0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,No Discount,0.0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,No Discount,0.0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,No Discount,0.0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,No Discount,0.0,Link Not Available,Tools_and_Brushes

In [26]:
df["Reviews"] = df["Reviews"].astype(int)
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695.0,660,5%,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899.0,746,17%,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430.0,409,5%,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789.0,655,17%,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499.0,399,20%,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,NaN,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,NaN,800,No Discount,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,NaN,2900,No Discount,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,NaN,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,NaN,1300,No Discount,0,Link Not Available,Tools_and_Brushes

In [27]:
df.dtypes

Product Name         object
Original Price      float64
Offer Price           int64
Discount             object
Reviews               int64
Images Links         object
product_category     object
dtype: object

In [28]:
df["Original Price"] = df["Original Price"].fillna(df["Offer Price"])
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695.0,660,5%,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899.0,746,17%,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430.0,409,5%,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789.0,655,17%,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499.0,399,20%,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,1300.0,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,800.0,800,No Discount,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,2900.0,2900,No Discount,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,1300.0,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,1300.0,1300,No Discount,0,Link Not Available,Tools_and_Brushes

In [29]:
df["Original Price"] = df["Original Price"].astype(int)
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,product_category
0,Orimii Bump Hydrating Body Butter for Reducing...,695,660,5%,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899,746,17%,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430,409,5%,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789,655,17%,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499,399,20%,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,1300,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,800,800,No Discount,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,2900,2900,No Discount,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,1300,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,1300,1300,No Discount,0,Link Not Available,Tools_and_Brushes

In [30]:
df = df.rename(columns={"product_category": "Product Category"})
df

,Product Name,Original Price,Offer Price,Discount,Reviews,Images Links,Product Category
0,Orimii Bump Hydrating Body Butter for Reducing...,695,660,5%,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899,746,17%,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430,409,5%,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789,655,17%,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499,399,20%,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,1300,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,800,800,No Discount,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,2900,2900,No Discount,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,1300,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,1300,1300,No Discount,0,Link Not Available,Tools_and_Brushes

In [31]:
df = df.rename(columns={"Discount": "Discount %"})
df

,Product Name,Original Price,Offer Price,Discount %,Reviews,Images Links,Product Category
0,Orimii Bump Hydrating Body Butter for Reducing...,695,660,5%,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899,746,17%,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430,409,5%,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789,655,17%,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499,399,20%,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,1300,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,800,800,No Discount,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,2900,2900,No Discount,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,1300,1300,No Discount,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,1300,1300,No Discount,0,Link Not Available,Tools_and_Brushes

In [32]:
df.dtypes

Product Name        object
Original Price       int64
Offer Price          int64
Discount %          object
Reviews              int64
Images Links        object
Product Category    object
dtype: object

In [38]:
df["Discount %"] = df["Discount %"].replace("No Discount", 0 )

In [39]:
df

,Product Name,Original Price,Offer Price,Discount %,Reviews,Images Links,Product Category
0,Orimii Bump Hydrating Body Butter for Reducing...,695,660,5,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899,746,17,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430,409,5,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789,655,17,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499,399,20,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,1300,1300,NaN,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,800,800,NaN,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,2900,2900,NaN,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,1300,1300,NaN,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,1300,1300,NaN,0,Link Not Available,Tools_and_Brushes

In [41]:
df["Discount %"] = df["Discount %"].fillna("0")
df

,Product Name,Original Price,Offer Price,Discount %,Reviews,Images Links,Product Category
0,Orimii Bump Hydrating Body Butter for Reducing...,695,660,5,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899,746,17,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430,409,5,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789,655,17,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499,399,20,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,800,800,0,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,2900,2900,0,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes

In [42]:
df["Discount %"] = df["Discount %"].str.replace("%", "", regex=False)
df

,Product Name,Original Price,Offer Price,Discount %,Reviews,Images Links,Product Category
0,Orimii Bump Hydrating Body Butter for Reducing...,695,660,5,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899,746,17,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430,409,5,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789,655,17,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499,399,20,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,800,800,0,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,2900,2900,0,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes

In [43]:
df.dtypes

Product Name        object
Original Price       int64
Offer Price          int64
Discount %          object
Reviews              int64
Images Links        object
Product Category    object
dtype: object

In [44]:
df["Discount %"] = df["Discount %"].astype(int)
df

,Product Name,Original Price,Offer Price,Discount %,Reviews,Images Links,Product Category
0,Orimii Bump Hydrating Body Butter for Reducing...,695,660,5,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899,746,17,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430,409,5,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789,655,17,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499,399,20,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,800,800,0,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,2900,2900,0,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes

In [45]:
df.dtypes

Product Name        object
Original Price       int64
Offer Price          int64
Discount %           int64
Reviews              int64
Images Links        object
Product Category    object
dtype: object

In [46]:
df.to_csv("Nayka_Cleaned.csv" , index = False)
df

,Product Name,Original Price,Offer Price,Discount %,Reviews,Images Links,Product Category
0,Orimii Bump Hydrating Body Butter for Reducing...,695,660,5,96,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
1,Cetaphil Moisturising Cream,899,746,17,146238,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
2,CeraVe Moisturizer Cream For Dry Skin With Cer...,430,409,5,41480,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
3,Cetaphil Moisturising Lotion,789,655,17,193928,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
4,Wishcare 10% AHA Blend + 1% Salicylic Acid Gly...,499,399,20,6701,https://images-static.nykaa.com/media/catalog/...,Body_Care_Products
...,...,...,...,...,...,...,...
34352,IDUN Minerals Eye & Lip Definer Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes
34353,IDUN Minerals Precision Eyeshadow Brush,800,800,0,0,Link Not Available,Tools_and_Brushes
34354,IDUN Minerals Powder Brush,2900,2900,0,0,Link Not Available,Tools_and_Brushes
34355,IDUN Minerals Concealer Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes
34356,IDUN Minerals Blending Brush,1300,1300,0,0,Link Not Available,Tools_and_Brushes